name: MTGCardScanner
options:
  bundleIdPrefix: com.nikoe.mtgcardscanner
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "55A7LPBS2U"
targets:
  MTGCardScanner:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.nikoe.mtgcardscanner
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_STRICT_CONCURRENCY: complete
        CODE_SIGN_STYLE: Automatic
    dependencies: []
  MTGCardScannerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: MTGCardScanner
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/MTGCardScanner.app/MTGCardScanner"
