import Foundation

// MARK: - InQuest Magazine Killer Decks

/// Actual decklists from InQuest Gamer magazine's "Killer Decks" column
/// and Spotlight insert cards (1995-1998). These are the specific lists
/// published in the magazine, NOT generic tournament archetypes.
/// InQuest ceased publication in 2007; these lists are historical
/// and will never change.
///
/// Sources: archive.org scans, magiclibrarities.net, tappedout.net,
/// mtgsalvation.com, mtggoldfish.com
enum InQuestDecks {

    static let all: [ClassicArchetype] = [
        // Killer Decks column — ordered by issue number
        bayouLightning,          // #1  May 1995
        fantasticFour,           // #2  Jun 1995
        theRack,                 // #3  Jul 1995
        wrathOfTitania,          // #7  Nov 1995
        leanGreenMachine,        // #9  Jan 1996
        omeletOnslaught,         // #13 May 1996
        dastardlyDenial,         // #16 Aug 1996
        deepwaterDeath,          // #20 Dec 1996
        nullVoid,                // #22 Feb 1997
        fireAndIce,              // #23 Mar 1997
        karateDeck,              // #24 Apr 1997
        dontEatMyLunch,          // #26 Jun 1997
        ultimate187,             // #33 Jan 1998
        playerHatersParadise,    // #41 Sep 1998
        stormCauldron,           // ~1997-1998
        shadowslayer,            // ~1997 Tempest era
        // Killer Decks Spotlight insert cards (1995-1996)
        spotlightDiscard,
        spotlightLandsEdge,
        spotlightGoblin,
        spotlightFaerie,
        spotlightZombie,
        spotlightGiants,
        spotlightMinotaur,
        spotlightPrimates,
    ]

    // MARK: - Issue #1 (May 1995) — Bayou Lightning

    static let bayouLightning = ClassicArchetype(
        id: "inquest-bayou-lightning",
        name: "#1 · Bayou Lightning",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Llanowar Elves": 4,
            "Elves of Deep Shadow": 4,
            "Juggernaut": 3,
            "Sengir Vampire": 2,
            "Carrion Ants": 1,
            "Fallen Angel": 1,
            "Force of Nature": 1,
            "Hypnotic Specter": 1,
            "Juzam Djinn": 1,
            "Royal Assassin": 1,
            "Sorceress Queen": 1,
            "Dark Ritual": 4,
            "Giant Growth": 4,
            "Howl from Beyond": 2,
            "Simulacrum": 2,
            "Berserk": 1,
            "Desert Twister": 2,
            "Hurricane": 2,
            "Demonic Tutor": 1,
            "Mind Twist": 1,
            "Regrowth": 1,
            "Tranquility": 1,
            "Fellwar Stone": 3,
            "Icy Manipulator": 1,
            "Bayou": 4,
            "Forest": 3,
            "Swamp": 2,
            "Strip Mine": 2,
            "Maze of Ith": 1,
            "Pendelhaven": 1,
            "Urborg": 1,
        ],
        sideboard: [
            "Deathgrip": 1,
            "Island of Wak-Wak": 1,
            "Lifeforce": 1,
            "Gloom": 1,
            "Pestilence": 1,
            "Simulacrum": 2,
            "Terror": 3,
            "Titania's Song": 1,
            "Tranquility": 2,
            "Tsunami": 1,
            "Underworld Dreams": 1,
        ],
        cardSets: [
            "Elves of Deep Shadow": "DRK", "Llanowar Elves": "LEA",
            "Carrion Ants": "LEG", "Fallen Angel": "LEG", "Force of Nature": "LEA",
            "Hypnotic Specter": "LEA", "Juggernaut": "LEA", "Juzam Djinn": "ARN",
            "Royal Assassin": "LEA", "Sengir Vampire": "LEA", "Sorceress Queen": "ARN",
            "Demonic Tutor": "LEA", "Desert Twister": "ARN", "Hurricane": "LEA",
            "Mind Twist": "LEA", "Regrowth": "LEA", "Tranquility": "LEA",
            "Berserk": "LEA", "Dark Ritual": "LEA", "Giant Growth": "LEA",
            "Howl from Beyond": "LEA", "Simulacrum": "LEA",
            "Fellwar Stone": "DRK", "Icy Manipulator": "LEA",
            "Bayou": "LEA", "Maze of Ith": "DRK", "Pendelhaven": "LEG",
            "Strip Mine": "ATQ", "Urborg": "LEG",
            "Forest": "ICE", "Swamp": "ICE",
            "Deathgrip": "LEA", "Island of Wak-Wak": "ARN", "Lifeforce": "LEA",
            "Gloom": "LEA", "Pestilence": "LEA", "Terror": "LEA",
            "Titania's Song": "ATQ", "Tsunami": "LEA", "Underworld Dreams": "LEG",
        ],
        cardTypes: [
            "Llanowar Elves": "Creature", "Elves of Deep Shadow": "Creature",
            "Juggernaut": "Creature", "Sengir Vampire": "Creature",
            "Carrion Ants": "Creature", "Fallen Angel": "Creature",
            "Force of Nature": "Creature", "Hypnotic Specter": "Creature",
            "Juzam Djinn": "Creature", "Royal Assassin": "Creature",
            "Sorceress Queen": "Creature", "Dark Ritual": "Instant",
            "Giant Growth": "Instant", "Howl from Beyond": "Instant",
            "Simulacrum": "Instant", "Berserk": "Instant",
            "Desert Twister": "Sorcery", "Hurricane": "Sorcery",
            "Demonic Tutor": "Sorcery", "Mind Twist": "Sorcery",
            "Regrowth": "Sorcery", "Tranquility": "Sorcery",
            "Fellwar Stone": "Artifact", "Icy Manipulator": "Artifact",
            "Bayou": "Land", "Maze of Ith": "Land", "Pendelhaven": "Land",
            "Strip Mine": "Land", "Urborg": "Land",
            "Deathgrip": "Enchantment", "Island of Wak-Wak": "Land",
            "Lifeforce": "Enchantment", "Gloom": "Enchantment",
            "Pestilence": "Enchantment", "Terror": "Instant",
            "Titania's Song": "Enchantment", "Tsunami": "Sorcery",
            "Underworld Dreams": "Enchantment",
        ],
        cardManaCosts: [
            "Llanowar Elves": "{G}", "Elves of Deep Shadow": "{B}",
            "Juggernaut": "{4}", "Sengir Vampire": "{3}{B}{B}",
            "Carrion Ants": "{2}{B}{B}", "Fallen Angel": "{3}{B}{B}",
            "Force of Nature": "{2}{G}{G}{G}{G}", "Hypnotic Specter": "{1}{B}{B}",
            "Juzam Djinn": "{2}{B}{B}", "Royal Assassin": "{1}{B}{B}",
            "Sorceress Queen": "{1}{B}{B}", "Dark Ritual": "{B}",
            "Giant Growth": "{G}", "Howl from Beyond": "{X}{B}",
            "Simulacrum": "{1}{B}", "Berserk": "{G}",
            "Desert Twister": "{4}{G}{G}", "Hurricane": "{X}{G}",
            "Demonic Tutor": "{1}{B}", "Mind Twist": "{X}{B}",
            "Regrowth": "{1}{G}", "Tranquility": "{1}{G}",
            "Fellwar Stone": "{2}", "Icy Manipulator": "{4}",
            "Deathgrip": "{B}{B}", "Lifeforce": "{G}{G}",
            "Gloom": "{2}{B}", "Pestilence": "{2}{B}{B}",
            "Terror": "{1}{B}", "Titania's Song": "{3}{G}",
            "Tsunami": "{3}{G}", "Underworld Dreams": "{B}{B}{B}",
        ],
        source: "InQuest Magazine Issue #1, May 1995. Designer: Michael Searle.",
        description: "\"To Beat the Moxes\" — a Green/Black speed deck that used mana creatures instead of Power Nine to deploy big threats fast. The first-ever InQuest Killer Deck. Featured Juzam Djinn, Force of Nature, and Sengir Vampire as finishers with Dark Ritual and mana elves for explosive starts."
    )

    // MARK: - Issue #2 (June 1995) — The Fantastic Four (Stasis Lock)

    static let fantasticFour = ClassicArchetype(
        id: "inquest-fantastic-four",
        name: "#2 · The Fantastic Four (Stasis Lock)",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Birds of Paradise": 4,
            "Serra Angel": 4,
            "Stasis": 4,
            "Instill Energy": 4,
            "Kismet": 3,
            "Copy Artifact": 1,
            "Sylvan Library": 1,
            "Black Vise": 4,
            "Icy Manipulator": 1,
            "Ivory Tower": 1,
            "Meekstone": 1,
            "Winter Orb": 1,
            "Ancestral Recall": 1,
            "Boomerang": 2,
            "Counterspell": 1,
            "Disenchant": 2,
            "Mana Drain": 3,
            "Power Sink": 1,
            "Psionic Blast": 2,
            "Reset": 2,
            "Twiddle": 2,
            "Armageddon": 1,
            "Braingeyser": 1,
            "Demonic Tutor": 1,
            "Regrowth": 1,
            "Time Walk": 1,
            "Island": 4,
            "Tropical Island": 4,
            "Tundra": 4,
            "Bayou": 1,
            "Library of Alexandria": 1,
        ],
        sideboard: [
            "Energy Flux": 2,
            "Gloom": 1,
            "Blue Elemental Blast": 3,
            "Disenchant": 2,
            "Siren's Call": 1,
            "Acid Rain": 1,
            "Balance": 1,
            "Psychic Purge": 3,
            "Tsunami": 1,
        ],
        cardSets: [
            "Birds of Paradise": "4ED", "Serra Angel": "4ED", "Stasis": "4ED",
            "Instill Energy": "4ED", "Kismet": "4ED", "Copy Artifact": "3ED",
            "Sylvan Library": "4ED", "Black Vise": "4ED", "Icy Manipulator": "4ED",
            "Ivory Tower": "4ED", "Meekstone": "4ED", "Winter Orb": "4ED",
            "Ancestral Recall": "LEA", "Boomerang": "4ED", "Counterspell": "4ED",
            "Disenchant": "4ED", "Mana Drain": "LEG", "Power Sink": "4ED",
            "Psionic Blast": "4ED", "Reset": "LEG", "Twiddle": "4ED",
            "Armageddon": "4ED", "Braingeyser": "3ED", "Demonic Tutor": "3ED",
            "Regrowth": "3ED", "Time Walk": "LEA",
            "Tropical Island": "3ED", "Tundra": "3ED", "Bayou": "3ED",
            "Library of Alexandria": "ARN", "Island": "ICE",
            "Energy Flux": "ATQ", "Gloom": "4ED", "Blue Elemental Blast": "4ED",
            "Siren's Call": "4ED", "Acid Rain": "4ED", "Balance": "4ED",
            "Psychic Purge": "DRK", "Tsunami": "4ED",
        ],
        cardTypes: [
            "Birds of Paradise": "Creature", "Serra Angel": "Creature",
            "Stasis": "Enchantment", "Instill Energy": "Enchantment",
            "Kismet": "Enchantment", "Copy Artifact": "Enchantment",
            "Sylvan Library": "Enchantment", "Black Vise": "Artifact",
            "Icy Manipulator": "Artifact", "Ivory Tower": "Artifact",
            "Meekstone": "Artifact", "Winter Orb": "Artifact",
            "Ancestral Recall": "Instant", "Boomerang": "Instant",
            "Counterspell": "Instant", "Disenchant": "Instant",
            "Mana Drain": "Instant", "Power Sink": "Instant",
            "Psionic Blast": "Instant", "Reset": "Instant",
            "Twiddle": "Instant", "Armageddon": "Sorcery",
            "Braingeyser": "Sorcery", "Demonic Tutor": "Sorcery",
            "Regrowth": "Sorcery", "Time Walk": "Sorcery",
            "Tropical Island": "Land", "Tundra": "Land", "Bayou": "Land",
            "Library of Alexandria": "Land",
            "Energy Flux": "Enchantment", "Gloom": "Enchantment",
            "Blue Elemental Blast": "Instant", "Siren's Call": "Instant",
            "Acid Rain": "Sorcery", "Balance": "Sorcery",
            "Psychic Purge": "Sorcery", "Tsunami": "Sorcery",
        ],
        cardManaCosts: [
            "Birds of Paradise": "{G}", "Serra Angel": "{3}{W}{W}",
            "Stasis": "{1}{U}", "Instill Energy": "{G}",
            "Kismet": "{3}{W}", "Copy Artifact": "{1}{U}",
            "Sylvan Library": "{1}{G}", "Black Vise": "{1}",
            "Icy Manipulator": "{4}", "Ivory Tower": "{1}",
            "Meekstone": "{1}", "Winter Orb": "{2}",
            "Ancestral Recall": "{U}", "Boomerang": "{U}{U}",
            "Counterspell": "{U}{U}", "Disenchant": "{1}{W}",
            "Mana Drain": "{U}{U}", "Power Sink": "{X}{U}",
            "Psionic Blast": "{2}{U}", "Reset": "{U}{U}",
            "Twiddle": "{U}", "Armageddon": "{3}{W}",
            "Braingeyser": "{X}{U}{U}", "Demonic Tutor": "{1}{B}",
            "Regrowth": "{1}{G}", "Time Walk": "{1}{U}",
            "Energy Flux": "{2}{U}", "Gloom": "{2}{B}",
            "Blue Elemental Blast": "{U}", "Siren's Call": "{U}",
            "Acid Rain": "{3}{U}", "Balance": "{1}{W}",
            "Psychic Purge": "{U}", "Tsunami": "{3}{G}",
        ],
        source: "InQuest Magazine Issue #2, June 1995.",
        description: "Lock the game with \"The Fantastic Four\" — Birds of Paradise + Instill Energy + Kismet + Stasis. Birds tap for mana through Stasis (via Instill Energy), Kismet prevents opponents from untapping, and Black Vise punishes the hand buildup. Serra Angel finishes while everything stays locked."
    )

    // MARK: - Issue #3 (July 1995) — The Rack

    static let theRack = ClassicArchetype(
        id: "inquest-the-rack",
        name: "#3 · The Rack",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Abyssal Specter": 4,
            "Hypnotic Specter": 4,
            "Black Knight": 4,
            "Dark Ritual": 4,
            "Hymn to Tourach": 4,
            "Mind Twist": 1,
            "Demonic Tutor": 1,
            "Lightning Bolt": 4,
            "Incinerate": 4,
            "The Rack": 4,
            "Disrupting Scepter": 2,
            "Zuran Orb": 1,
            "Disenchant": 3,
            "Balance": 1,
            "Scrubland": 2,
            "Badlands": 4,
            "Sulfurous Springs": 2,
            "City of Brass": 2,
            "Swamp": 6,
            "Strip Mine": 2,
            "Mishra's Factory": 1,
        ],
        sideboard: [
            "Land Tax": 2,
            "Pyroblast": 4,
            "Disenchant": 1,
            "Gloom": 2,
            "Simulacrum": 3,
            "Ghostly Flame": 1,
            "Curse of Marit Lage": 2,
        ],
        cardSets: [
            "Abyssal Specter": "ICE", "Hypnotic Specter": "4ED",
            "Black Knight": "4ED", "Dark Ritual": "ICE", "Hymn to Tourach": "FEM",
            "Mind Twist": "3ED", "Demonic Tutor": "3ED", "Lightning Bolt": "4ED",
            "Incinerate": "ICE", "The Rack": "ATQ", "Disrupting Scepter": "4ED",
            "Zuran Orb": "ICE", "Disenchant": "4ED", "Balance": "4ED",
            "Scrubland": "3ED", "Badlands": "3ED", "Sulfurous Springs": "ICE",
            "City of Brass": "CHR", "Strip Mine": "ATQ", "Mishra's Factory": "ATQ",
            "Swamp": "ICE",
            "Land Tax": "LEG", "Pyroblast": "ICE", "Gloom": "4ED",
            "Simulacrum": "4ED", "Ghostly Flame": "ICE", "Curse of Marit Lage": "ICE",
        ],
        cardTypes: [
            "Abyssal Specter": "Creature", "Hypnotic Specter": "Creature",
            "Black Knight": "Creature", "Dark Ritual": "Instant",
            "Hymn to Tourach": "Sorcery", "Mind Twist": "Sorcery",
            "Demonic Tutor": "Sorcery", "Lightning Bolt": "Instant",
            "Incinerate": "Instant", "The Rack": "Artifact",
            "Disrupting Scepter": "Artifact", "Zuran Orb": "Artifact",
            "Disenchant": "Instant", "Balance": "Sorcery",
            "Scrubland": "Land", "Badlands": "Land",
            "Sulfurous Springs": "Land", "City of Brass": "Land",
            "Strip Mine": "Land", "Mishra's Factory": "Land",
            "Land Tax": "Enchantment", "Pyroblast": "Instant",
            "Gloom": "Enchantment", "Simulacrum": "Instant",
            "Ghostly Flame": "Enchantment", "Curse of Marit Lage": "Enchantment",
        ],
        cardManaCosts: [
            "Abyssal Specter": "{2}{B}{B}", "Hypnotic Specter": "{1}{B}{B}",
            "Black Knight": "{B}{B}", "Dark Ritual": "{B}",
            "Hymn to Tourach": "{B}{B}", "Mind Twist": "{X}{B}",
            "Demonic Tutor": "{1}{B}", "Lightning Bolt": "{R}",
            "Incinerate": "{1}{R}", "The Rack": "{1}",
            "Disrupting Scepter": "{3}", "Zuran Orb": "{0}",
            "Disenchant": "{1}{W}", "Balance": "{1}{W}",
            "Land Tax": "{W}", "Pyroblast": "{R}",
            "Gloom": "{2}{B}", "Simulacrum": "{1}{B}",
            "Ghostly Flame": "{1}{B}{R}", "Curse of Marit Lage": "{3}{U}{U}",
        ],
        source: "InQuest Magazine Issue #3, July 1995. Designer: Douglas Goldstein.",
        description: "Discard-based aggro-control. Hymn to Tourach and Hypnotic Specter shred the opponent's hand while The Rack punishes them for having fewer than 3 cards. Lightning Bolt and Incinerate provide removal and reach. A classic InQuest design that combined three colors for maximum disruption."
    )

    // MARK: - Issue #7 (November 1995) — Wrath of Titania

    static let wrathOfTitania = ClassicArchetype(
        id: "inquest-wrath-of-titania",
        name: "#7 · Wrath of Titania",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Titania's Song": 1,
            "Wrath of God": 3,
            "Lightning Bolt": 4,
            "Disenchant": 4,
            "Armageddon": 1,
            "Swords to Plowshares": 4,
            "Fellwar Stone": 4,
            "Mana Vault": 2,
            "Icy Manipulator": 2,
            "Nevinyrral's Disk": 1,
            "Black Vise": 1,
            "Jayemdae Tome": 1,
            "Jade Monolith": 1,
            "Shield of the Ages": 1,
            "Iron Star": 1,
            "Marble Diamond": 2,
            "Fire Diamond": 2,
            "Serra Angel": 2,
            "Karplusan Forest": 4,
            "Brushland": 4,
            "City of Brass": 1,
            "Plains": 6,
            "Strip Mine": 2,
            "Mishra's Factory": 4,
            "Mountain": 2,
        ],
        sideboard: [
            "Pyroblast": 3,
            "Tsunami": 2,
            "Energy Storm": 2,
            "Drought": 2,
            "Land Tax": 1,
            "Reverse Damage": 1,
            "Circle of Protection: Red": 2,
            "Divine Offering": 2,
        ],
        cardSets: [
            "Titania's Song": "ATQ", "Wrath of God": "4ED", "Lightning Bolt": "4ED",
            "Disenchant": "4ED", "Armageddon": "4ED", "Swords to Plowshares": "ICE",
            "Fellwar Stone": "4ED", "Mana Vault": "4ED", "Icy Manipulator": "4ED",
            "Nevinyrral's Disk": "4ED", "Black Vise": "4ED", "Jayemdae Tome": "4ED",
            "Jade Monolith": "4ED", "Shield of the Ages": "ICE", "Iron Star": "4ED",
            "Marble Diamond": "MIR", "Fire Diamond": "MIR", "Serra Angel": "4ED",
            "Karplusan Forest": "ICE", "Brushland": "ICE", "City of Brass": "CHR",
            "Strip Mine": "ATQ", "Mishra's Factory": "ATQ",
            "Plains": "ICE", "Mountain": "ICE",
            "Pyroblast": "ICE", "Tsunami": "4ED", "Energy Storm": "ICE",
            "Drought": "ICE", "Land Tax": "LEG", "Reverse Damage": "4ED",
            "Circle of Protection: Red": "ICE", "Divine Offering": "ICE",
        ],
        cardTypes: [
            "Titania's Song": "Enchantment", "Wrath of God": "Sorcery",
            "Lightning Bolt": "Instant", "Disenchant": "Instant",
            "Armageddon": "Sorcery", "Swords to Plowshares": "Instant",
            "Fellwar Stone": "Artifact", "Mana Vault": "Artifact",
            "Icy Manipulator": "Artifact", "Nevinyrral's Disk": "Artifact",
            "Black Vise": "Artifact", "Jayemdae Tome": "Artifact",
            "Jade Monolith": "Artifact", "Shield of the Ages": "Artifact",
            "Iron Star": "Artifact", "Marble Diamond": "Artifact",
            "Fire Diamond": "Artifact", "Serra Angel": "Creature",
            "Karplusan Forest": "Land", "Brushland": "Land",
            "City of Brass": "Land", "Strip Mine": "Land",
            "Mishra's Factory": "Land",
            "Pyroblast": "Instant", "Tsunami": "Sorcery",
            "Energy Storm": "Enchantment", "Drought": "Enchantment",
            "Land Tax": "Enchantment", "Reverse Damage": "Instant",
            "Circle of Protection: Red": "Enchantment",
            "Divine Offering": "Instant",
        ],
        cardManaCosts: [
            "Titania's Song": "{3}{G}", "Wrath of God": "{2}{W}{W}",
            "Lightning Bolt": "{R}", "Disenchant": "{1}{W}",
            "Armageddon": "{3}{W}", "Swords to Plowshares": "{W}",
            "Fellwar Stone": "{2}", "Mana Vault": "{1}",
            "Icy Manipulator": "{4}", "Nevinyrral's Disk": "{4}",
            "Black Vise": "{1}", "Jayemdae Tome": "{4}",
            "Jade Monolith": "{4}", "Shield of the Ages": "{2}",
            "Iron Star": "{1}", "Marble Diamond": "{2}",
            "Fire Diamond": "{2}", "Serra Angel": "{3}{W}{W}",
            "Pyroblast": "{R}", "Tsunami": "{3}{G}",
            "Energy Storm": "{1}{W}", "Drought": "{2}{W}{W}",
            "Land Tax": "{W}", "Reverse Damage": "{1}{W}{W}",
            "Circle of Protection: Red": "{1}{W}",
            "Divine Offering": "{1}{W}",
        ],
        source: "InQuest Magazine Issue #7, November 1995. Designer: Jeff Hannes.",
        description: "Load artifacts for defense, then Wrath of God + Armageddon + Titania's Song to turn all your artifacts into creatures. Your Fellwar Stones become 2/2s, Mana Vaults become 3/3s, and Icy Manipulators become 4/4s — an instant army after clearing the board."
    )

    // MARK: - Issue #13 (May 1996) — Omelet Onslaught

    static let omeletOnslaught = ClassicArchetype(
        id: "inquest-omelet-onslaught",
        name: "#13 · Omelet Onslaught",
        era: "1996",
        format: "Type I",
        mainboard: [
            "Rukh Egg": 4,
            "Tinder Wall": 4,
            "Kjeldoran Dead": 3,
            "Will-o'-the-Wisp": 2,
            "Animate Dead": 3,
            "Jokulhaups": 3,
            "Fireball": 2,
            "Wheel of Fortune": 1,
            "Regrowth": 1,
            "Tranquility": 1,
            "Demonic Tutor": 1,
            "Dark Ritual": 4,
            "Burnt Offering": 3,
            "Giant Growth": 2,
            "Simulacrum": 2,
            "Mana Vault": 2,
            "Nevinyrral's Disk": 1,
            "Zuran Orb": 1,
            "Despotic Scepter": 1,
            "Feldon's Cane": 1,
            "Swamp": 8,
            "Forest": 6,
            "Mountain": 3,
            "Badlands": 2,
        ],
        sideboard: [
            "Red Elemental Blast": 4,
            "Blood Moon": 2,
            "Gloom": 2,
            "Simulacrum": 2,
            "Flashfires": 2,
            "Curse of Marit Lage": 1,
            "Anarchy": 1,
            "Tranquility": 1,
        ],
        cardSets: [
            "Rukh Egg": "ARN", "Tinder Wall": "ICE", "Kjeldoran Dead": "ICE",
            "Will-o'-the-Wisp": "4ED", "Animate Dead": "4ED", "Jokulhaups": "ICE",
            "Fireball": "4ED", "Wheel of Fortune": "4ED", "Regrowth": "4ED",
            "Tranquility": "4ED", "Demonic Tutor": "3ED", "Dark Ritual": "ICE",
            "Burnt Offering": "ICE", "Giant Growth": "4ED", "Simulacrum": "4ED",
            "Mana Vault": "4ED", "Nevinyrral's Disk": "4ED", "Zuran Orb": "ICE",
            "Despotic Scepter": "ICE", "Feldon's Cane": "ATQ",
            "Badlands": "3ED",
            "Swamp": "ICE", "Forest": "ICE", "Mountain": "ICE",
            "Red Elemental Blast": "4ED", "Blood Moon": "DRK", "Gloom": "4ED",
            "Flashfires": "4ED", "Curse of Marit Lage": "ICE", "Anarchy": "ICE",
        ],
        cardTypes: [
            "Rukh Egg": "Creature", "Tinder Wall": "Creature",
            "Kjeldoran Dead": "Creature", "Will-o'-the-Wisp": "Creature",
            "Animate Dead": "Enchantment", "Jokulhaups": "Sorcery",
            "Fireball": "Sorcery", "Wheel of Fortune": "Sorcery",
            "Regrowth": "Sorcery", "Tranquility": "Sorcery",
            "Demonic Tutor": "Sorcery", "Dark Ritual": "Instant",
            "Burnt Offering": "Instant", "Giant Growth": "Instant",
            "Simulacrum": "Instant", "Mana Vault": "Artifact",
            "Nevinyrral's Disk": "Artifact", "Zuran Orb": "Artifact",
            "Despotic Scepter": "Artifact", "Feldon's Cane": "Artifact",
            "Badlands": "Land",
            "Red Elemental Blast": "Instant", "Blood Moon": "Enchantment",
            "Gloom": "Enchantment", "Flashfires": "Sorcery",
            "Curse of Marit Lage": "Enchantment", "Anarchy": "Sorcery",
        ],
        cardManaCosts: [
            "Rukh Egg": "{3}{R}", "Tinder Wall": "{G}",
            "Kjeldoran Dead": "{B}", "Will-o'-the-Wisp": "{B}",
            "Animate Dead": "{1}{B}", "Jokulhaups": "{4}{R}{R}",
            "Fireball": "{X}{R}", "Wheel of Fortune": "{2}{R}",
            "Regrowth": "{1}{G}", "Tranquility": "{1}{G}",
            "Demonic Tutor": "{1}{B}", "Dark Ritual": "{B}",
            "Burnt Offering": "{B}", "Giant Growth": "{G}",
            "Simulacrum": "{1}{B}", "Mana Vault": "{1}",
            "Nevinyrral's Disk": "{4}", "Zuran Orb": "{0}",
            "Despotic Scepter": "{1}", "Feldon's Cane": "{1}",
            "Red Elemental Blast": "{R}", "Blood Moon": "{2}{R}",
            "Gloom": "{2}{B}", "Flashfires": "{3}{R}",
            "Curse of Marit Lage": "{3}{U}{U}", "Anarchy": "{2}{R}{R}",
        ],
        source: "InQuest Magazine Issue #13, May 1996.",
        description: "\"Eggs Over Easy\" — sacrifice Rukh Eggs (via Burnt Offering, Kjeldoran Dead, or Despotic Scepter) to get 4/4 flying Bird tokens, then cast Jokulhaups to destroy all lands, artifacts, and creatures while your Rukh tokens survive. A creative combo that turned breakfast into destruction."
    )

    // MARK: - Storm Cauldron Combo (~1997-1998)

    static let stormCauldron = ClassicArchetype(
        id: "inquest-storm-cauldron",
        name: "Storm Cauldron Combo",  // issue unknown
        era: "1997",
        format: "Type I",
        mainboard: [
            "Storm Cauldron": 4,
            "Fastbond": 2,
            "Zuran Orb": 1,
            "Ivory Tower": 2,
            "Howling Mine": 4,
            "Stormbind": 2,
            "Sylvan Library": 2,
            "Birds of Paradise": 4,
            "Black Vise": 2,
            "Mana Vault": 1,
            "Sol Ring": 1,
            "Regrowth": 1,
            "Demonic Tutor": 1,
            "Channel": 1,
            "Fireball": 2,
            "Lightning Bolt": 4,
            "Counterspell": 2,
            "Sheltered Valley": 2,
            "Taiga": 4,
            "Tropical Island": 3,
            "Volcanic Island": 2,
            "City of Brass": 2,
            "Forest": 4,
            "Mountain": 3,
            "Island": 3,
        ],
        sideboard: [
            "Red Elemental Blast": 3,
            "Blue Elemental Blast": 2,
            "Tranquility": 2,
            "Earthquake": 2,
            "Pyroblast": 2,
            "Tormod's Crypt": 2,
            "Mana Short": 2,
        ],
        cardSets: [
            "Storm Cauldron": "ALL", "Fastbond": "3ED", "Zuran Orb": "ICE",
            "Ivory Tower": "4ED", "Howling Mine": "4ED", "Stormbind": "ICE",
            "Sylvan Library": "5ED", "Birds of Paradise": "5ED",
            "Black Vise": "4ED", "Mana Vault": "5ED", "Sol Ring": "3ED",
            "Regrowth": "3ED", "Demonic Tutor": "3ED", "Channel": "4ED",
            "Fireball": "5ED", "Lightning Bolt": "4ED", "Counterspell": "5ED",
            "Sheltered Valley": "ALL", "Taiga": "3ED", "Tropical Island": "3ED",
            "Volcanic Island": "3ED", "City of Brass": "5ED",
            "Forest": "5ED", "Mountain": "5ED", "Island": "5ED",
            "Red Elemental Blast": "4ED", "Blue Elemental Blast": "4ED",
            "Tranquility": "5ED", "Earthquake": "5ED", "Pyroblast": "ICE",
            "Tormod's Crypt": "DRK", "Mana Short": "4ED",
        ],
        cardTypes: [
            "Storm Cauldron": "Artifact", "Fastbond": "Enchantment",
            "Zuran Orb": "Artifact", "Ivory Tower": "Artifact",
            "Howling Mine": "Artifact", "Stormbind": "Enchantment",
            "Sylvan Library": "Enchantment", "Birds of Paradise": "Creature",
            "Black Vise": "Artifact", "Mana Vault": "Artifact",
            "Sol Ring": "Artifact", "Regrowth": "Sorcery",
            "Demonic Tutor": "Sorcery", "Channel": "Sorcery",
            "Fireball": "Sorcery", "Lightning Bolt": "Instant",
            "Counterspell": "Instant",
            "Sheltered Valley": "Land", "Taiga": "Land",
            "Tropical Island": "Land", "Volcanic Island": "Land",
            "City of Brass": "Land",
            "Red Elemental Blast": "Instant", "Blue Elemental Blast": "Instant",
            "Tranquility": "Sorcery", "Earthquake": "Sorcery",
            "Pyroblast": "Instant", "Tormod's Crypt": "Artifact",
            "Mana Short": "Instant",
        ],
        cardManaCosts: [
            "Storm Cauldron": "{5}", "Fastbond": "{G}",
            "Zuran Orb": "{0}", "Ivory Tower": "{1}",
            "Howling Mine": "{2}", "Stormbind": "{1}{R}{G}",
            "Sylvan Library": "{1}{G}", "Birds of Paradise": "{G}",
            "Black Vise": "{1}", "Mana Vault": "{1}",
            "Sol Ring": "{1}", "Regrowth": "{1}{G}",
            "Demonic Tutor": "{1}{B}", "Channel": "{G}{G}",
            "Fireball": "{X}{R}", "Lightning Bolt": "{R}",
            "Counterspell": "{U}{U}",
            "Red Elemental Blast": "{R}", "Blue Elemental Blast": "{U}",
            "Tranquility": "{1}{G}", "Earthquake": "{X}{R}",
            "Pyroblast": "{R}", "Tormod's Crypt": "{0}",
            "Mana Short": "{2}{U}",
        ],
        source: "InQuest Magazine, circa 1997-1998.",
        description: "Storm Cauldron bounces lands to hand when tapped. Combined with Fastbond (play unlimited lands) and Zuran Orb (sacrifice lands for life), you generate infinite mana and life. Ivory Tower gains life from your huge hand, Howling Mine refills, and Stormbind/Fireball finish the opponent."
    )

    // MARK: - Spotlight Insert: The Discard Deck (Issue #3, July 1995)

    static let spotlightDiscard = ClassicArchetype(
        id: "inquest-spotlight-discard",
        name: "#3 · Spotlight: The Discard Deck",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Gwendlyn Di Corci": 1,
            "Hypnotic Specter": 4,
            "Mindstab Thrull": 4,
            "Cursed Rack": 2,
            "Disrupting Scepter": 1,
            "Hymn to Tourach": 4,
            "Mind Twist": 1,
            "Copy Artifact": 1,
            "The Rack": 4,
            "Storm World": 1,
            "Badlands": 4,
            "City of Brass": 1,
            "Dark Ritual": 4,
            "Mox Jet": 1,
            "Mox Pearl": 1,
            "Mox Ruby": 1,
            "Mox Sapphire": 1,
            "Scrubland": 4,
            "Underground Sea": 4,
            "Animate Dead": 1,
            "Demonic Tutor": 1,
            "Disenchant": 2,
            "Drain Life": 1,
            "Lightning Bolt": 3,
            "Maze of Ith": 1,
            "Power Sink": 2,
            "Spell Blast": 1,
            "Swords to Plowshares": 1,
            "Terror": 1,
            "Transmute Artifact": 1,
            "Underworld Dreams": 1,
            "Swamp": 1,
        ],
        cardSets: [
            "Gwendlyn Di Corci": "LEG", "Hypnotic Specter": "4ED",
            "Mindstab Thrull": "FEM", "Cursed Rack": "ATQ",
            "Disrupting Scepter": "4ED", "Hymn to Tourach": "FEM",
            "Mind Twist": "3ED", "Copy Artifact": "3ED", "The Rack": "ATQ",
            "Storm World": "LEG", "Badlands": "3ED", "City of Brass": "CHR",
            "Dark Ritual": "ICE", "Mox Jet": "LEA", "Mox Pearl": "LEA",
            "Mox Ruby": "LEA", "Mox Sapphire": "LEA", "Scrubland": "3ED",
            "Underground Sea": "3ED", "Animate Dead": "4ED", "Demonic Tutor": "3ED",
            "Disenchant": "4ED", "Drain Life": "4ED", "Lightning Bolt": "4ED",
            "Maze of Ith": "DRK", "Power Sink": "4ED", "Spell Blast": "4ED",
            "Swords to Plowshares": "ICE", "Terror": "4ED",
            "Transmute Artifact": "ATQ", "Underworld Dreams": "LEG",
            "Swamp": "ICE",
        ],
        cardTypes: [
            "Gwendlyn Di Corci": "Creature", "Hypnotic Specter": "Creature",
            "Mindstab Thrull": "Creature", "Cursed Rack": "Artifact",
            "Disrupting Scepter": "Artifact", "Hymn to Tourach": "Sorcery",
            "Mind Twist": "Sorcery", "Copy Artifact": "Enchantment",
            "The Rack": "Artifact", "Storm World": "Enchantment",
            "Badlands": "Land", "City of Brass": "Land",
            "Dark Ritual": "Instant", "Mox Jet": "Artifact",
            "Mox Pearl": "Artifact", "Mox Ruby": "Artifact",
            "Mox Sapphire": "Artifact", "Scrubland": "Land",
            "Underground Sea": "Land", "Animate Dead": "Enchantment",
            "Demonic Tutor": "Sorcery", "Disenchant": "Instant",
            "Drain Life": "Sorcery", "Lightning Bolt": "Instant",
            "Maze of Ith": "Land", "Power Sink": "Instant",
            "Spell Blast": "Instant", "Swords to Plowshares": "Instant",
            "Terror": "Instant", "Transmute Artifact": "Sorcery",
            "Underworld Dreams": "Enchantment",
        ],
        cardManaCosts: [
            "Gwendlyn Di Corci": "{U}{B}{B}{R}", "Hypnotic Specter": "{1}{B}{B}",
            "Mindstab Thrull": "{1}{B}{B}", "Cursed Rack": "{4}",
            "Disrupting Scepter": "{3}", "Hymn to Tourach": "{B}{B}",
            "Mind Twist": "{X}{B}", "Copy Artifact": "{1}{U}",
            "The Rack": "{1}", "Storm World": "{R}",
            "Dark Ritual": "{B}", "Mox Jet": "{0}",
            "Mox Pearl": "{0}", "Mox Ruby": "{0}",
            "Mox Sapphire": "{0}", "Animate Dead": "{1}{B}",
            "Demonic Tutor": "{1}{B}", "Disenchant": "{1}{W}",
            "Drain Life": "{X}{1}{B}", "Lightning Bolt": "{R}",
            "Power Sink": "{X}{U}", "Spell Blast": "{X}{U}",
            "Swords to Plowshares": "{W}", "Terror": "{1}{B}",
            "Transmute Artifact": "{U}{U}",
            "Underworld Dreams": "{B}{B}{B}",
        ],
        source: "InQuest Magazine Issue #3, July 1995. Killer Decks Spotlight insert card. Source: magiclibrarities.net.",
        description: "A Spotlight insert card deck focused on shredding the opponent's hand. Hypnotic Specter and Hymn to Tourach strip cards, The Rack and Cursed Rack deal damage for each missing card, and Gwendlyn Di Corci provides repeatable discard. Four-color manabase powered by Moxes."
    )

    // MARK: - Spotlight Insert: The Land's Edge Deck (Issue #4, August 1995)

    static let spotlightLandsEdge = ClassicArchetype(
        id: "inquest-spotlight-lands-edge",
        name: "#4 · Spotlight: Land's Edge",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Land Tax": 4,
            "Land's Edge": 4,
            "Circle of Protection: Red": 2,
            "Serra Angel": 4,
            "Mountain": 5,
            "Mox Pearl": 1,
            "Mox Ruby": 1,
            "Plains": 12,
            "Plateau": 4,
            "Armageddon": 2,
            "Balance": 1,
            "Disenchant": 3,
            "Lightning Bolt": 4,
            "Swords to Plowshares": 4,
            "Wrath of God": 2,
            "Ivory Tower": 1,
            "Library of Leng": 2,
            "Reverse Damage": 2,
            "Skull of Orm": 1,
            "Wheel of Fortune": 1,
        ],
        cardSets: [
            "Land Tax": "LEG", "Land's Edge": "CHR", "Circle of Protection: Red": "ICE",
            "Serra Angel": "4ED", "Mox Pearl": "LEA", "Mox Ruby": "LEA",
            "Plateau": "3ED", "Mountain": "ICE", "Plains": "ICE",
            "Armageddon": "4ED", "Balance": "4ED",
            "Disenchant": "4ED", "Lightning Bolt": "4ED",
            "Swords to Plowshares": "ICE", "Wrath of God": "4ED",
            "Ivory Tower": "4ED", "Library of Leng": "4ED",
            "Reverse Damage": "4ED", "Skull of Orm": "4ED",
            "Wheel of Fortune": "4ED",
        ],
        cardTypes: [
            "Land Tax": "Enchantment", "Land's Edge": "Enchantment",
            "Circle of Protection: Red": "Enchantment",
            "Serra Angel": "Creature", "Mox Pearl": "Artifact",
            "Mox Ruby": "Artifact", "Plateau": "Land",
            "Armageddon": "Sorcery", "Balance": "Sorcery",
            "Disenchant": "Instant", "Lightning Bolt": "Instant",
            "Swords to Plowshares": "Instant", "Wrath of God": "Sorcery",
            "Ivory Tower": "Artifact", "Library of Leng": "Artifact",
            "Reverse Damage": "Instant", "Skull of Orm": "Artifact",
            "Wheel of Fortune": "Sorcery",
        ],
        cardManaCosts: [
            "Land Tax": "{W}", "Land's Edge": "{1}{R}{R}",
            "Circle of Protection: Red": "{1}{W}",
            "Serra Angel": "{3}{W}{W}", "Mox Pearl": "{0}",
            "Mox Ruby": "{0}", "Armageddon": "{3}{W}",
            "Balance": "{1}{W}", "Disenchant": "{1}{W}",
            "Lightning Bolt": "{R}", "Swords to Plowshares": "{W}",
            "Wrath of God": "{2}{W}{W}", "Ivory Tower": "{1}",
            "Library of Leng": "{1}", "Reverse Damage": "{1}{W}{W}",
            "Skull of Orm": "{3}", "Wheel of Fortune": "{2}{R}",
        ],
        source: "InQuest Magazine Issue #4, August 1995. Killer Decks Spotlight insert card. Source: magiclibrarities.net.",
        description: "Land Tax fetches 3 lands per turn, Land's Edge discards them to deal 2 damage each. With Library of Leng you can put discarded lands on top of your library instead of the graveyard, then Land Tax fetches them again — infinite 2-damage pings. Serra Angel and burn provide backup."
    )

    // MARK: - Spotlight Insert: The Goblin Deck (Issue #5, September 1995)

    static let spotlightGoblin = ClassicArchetype(
        id: "inquest-spotlight-goblin",
        name: "#5 · Spotlight: Goblin Tribal",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Goblin Balloon Brigade": 4,
            "Goblin Chirurgeon": 3,
            "Goblin Digging Team": 4,
            "Goblin King": 4,
            "Goblin Snowman": 1,
            "Goblins of the Flarg": 4,
            "Gauntlet of Might": 1,
            "Goblin Caves": 4,
            "Goblin Shrine": 4,
            "Goblin Warrens": 2,
            "Blood Moon": 2,
            "Disenchant": 2,
            "Gravity Sphere": 1,
            "Fireball": 3,
            "Lightning Bolt": 3,
            "Maze of Ith": 1,
            "Swords to Plowshares": 2,
            "Dwarven Hold": 1,
            "Mountain": 9,
            "Mox Ruby": 1,
            "Plains": 3,
            "Plateau": 4,
            "Sol Ring": 1,
            "Strip Mine": 2,
        ],
        cardSets: [
            "Goblin Balloon Brigade": "4ED", "Goblin Chirurgeon": "FEM",
            "Goblin Digging Team": "DRK", "Goblin King": "4ED",
            "Goblin Snowman": "ICE", "Goblins of the Flarg": "DRK",
            "Gauntlet of Might": "LEA", "Goblin Caves": "DRK",
            "Goblin Shrine": "DRK", "Goblin Warrens": "FEM",
            "Blood Moon": "DRK", "Disenchant": "4ED", "Gravity Sphere": "LEG",
            "Fireball": "4ED", "Lightning Bolt": "4ED", "Maze of Ith": "DRK",
            "Swords to Plowshares": "ICE", "Dwarven Hold": "FEM",
            "Mox Ruby": "LEA", "Plateau": "3ED", "Sol Ring": "3ED",
            "Strip Mine": "ATQ",
            "Mountain": "ICE", "Plains": "ICE",
        ],
        cardTypes: [
            "Goblin Balloon Brigade": "Creature", "Goblin Chirurgeon": "Creature",
            "Goblin Digging Team": "Creature", "Goblin King": "Creature",
            "Goblin Snowman": "Creature", "Goblins of the Flarg": "Creature",
            "Gauntlet of Might": "Artifact", "Goblin Caves": "Enchantment",
            "Goblin Shrine": "Enchantment", "Goblin Warrens": "Enchantment",
            "Blood Moon": "Enchantment", "Disenchant": "Instant",
            "Gravity Sphere": "Enchantment", "Fireball": "Sorcery",
            "Lightning Bolt": "Instant", "Maze of Ith": "Land",
            "Swords to Plowshares": "Instant", "Dwarven Hold": "Land",
            "Mox Ruby": "Artifact", "Plateau": "Land",
            "Sol Ring": "Artifact", "Strip Mine": "Land",
        ],
        cardManaCosts: [
            "Goblin Balloon Brigade": "{R}", "Goblin Chirurgeon": "{R}",
            "Goblin Digging Team": "{R}", "Goblin King": "{1}{R}{R}",
            "Goblin Snowman": "{3}{R}", "Goblins of the Flarg": "{1}{R}",
            "Gauntlet of Might": "{4}", "Goblin Caves": "{1}{R}{R}",
            "Goblin Shrine": "{1}{R}{R}", "Goblin Warrens": "{2}{R}",
            "Blood Moon": "{2}{R}", "Disenchant": "{1}{W}",
            "Gravity Sphere": "{2}{R}", "Fireball": "{X}{R}",
            "Lightning Bolt": "{R}", "Swords to Plowshares": "{W}",
            "Mox Ruby": "{0}", "Sol Ring": "{1}",
        ],
        source: "InQuest Magazine Issue #5, September 1995. Killer Decks Spotlight insert card. Source: magiclibrarities.net.",
        description: "Classic Goblin tribal from 1995. Goblin King makes all Goblins mountainwalk, Goblin Caves and Goblin Shrine pump the team, Gauntlet of Might doubles red mana and gives +1/+1. Goblin Warrens generates tokens for a swarm finish. Blood Moon turns all nonbasics into Mountains for the King's mountainwalk."
    )

    // MARK: - Issue #9 (January 1996) — Lean Green Machine

    static let leanGreenMachine = ClassicArchetype(
        id: "inquest-lean-green-machine",
        name: "#9 · Lean Green Machine",
        era: "1996",
        format: "Type I",
        mainboard: [
            "Autumn Willow": 1,
            "Erhnam Djinn": 3,
            "Force of Nature": 1,
            "Fyndhorn Elder": 2,
            "Fyndhorn Elves": 4,
            "Hungry Mist": 2,
            "Johtull Wurm": 1,
            "Killer Bees": 2,
            "Llanowar Elves": 4,
            "Scaled Wurm": 1,
            "Tinder Wall": 3,
            "An-Havva Inn": 1,
            "Crumble": 2,
            "Desert Twister": 1,
            "Giant Growth": 4,
            "Hurricane": 1,
            "Lure": 1,
            "Primal Order": 1,
            "Regrowth": 1,
            "Stampede": 1,
            "Tranquility": 1,
            "Lightning Bolt": 2,
            "Wheel of Fortune": 1,
            "Feldon's Cane": 1,
            "Sol Ring": 1,
            "Zuran Orb": 1,
            "Forest": 13,
            "Pendelhaven": 1,
            "Strip Mine": 2,
            "Taiga": 2,
        ],
        sideboard: [
            "Crumble": 1,
            "Lifeforce": 3,
            "Lightning Bolt": 2,
            "Sandstorm": 1,
            "Shatterstorm": 2,
            "Tranquility": 3,
            "Tsunami": 3,
        ],
        cardSets: [
            "Autumn Willow": "HML", "Erhnam Djinn": "ARN", "Force of Nature": "LEA",
            "Fyndhorn Elder": "ICE", "Fyndhorn Elves": "ICE", "Hungry Mist": "HML",
            "Johtull Wurm": "ICE", "Killer Bees": "LEG", "Llanowar Elves": "LEA",
            "Scaled Wurm": "ICE", "Tinder Wall": "ICE",
            "An-Havva Inn": "HML", "Crumble": "ATQ", "Desert Twister": "ARN",
            "Giant Growth": "LEA", "Hurricane": "LEA", "Lure": "LEA",
            "Primal Order": "HML", "Regrowth": "LEA", "Stampede": "ICE",
            "Tranquility": "LEA", "Lightning Bolt": "LEA", "Wheel of Fortune": "LEA",
            "Feldon's Cane": "ATQ", "Sol Ring": "LEA", "Zuran Orb": "ICE",
            "Pendelhaven": "LEG", "Strip Mine": "ATQ", "Taiga": "LEA",
            "Forest": "ICE",
            "Lifeforce": "LEA", "Sandstorm": "ARN", "Shatterstorm": "ATQ", "Tsunami": "LEA",
        ],
        cardTypes: [
            "Autumn Willow": "Creature", "Erhnam Djinn": "Creature",
            "Force of Nature": "Creature", "Fyndhorn Elder": "Creature",
            "Fyndhorn Elves": "Creature", "Hungry Mist": "Creature",
            "Johtull Wurm": "Creature", "Killer Bees": "Creature",
            "Llanowar Elves": "Creature", "Scaled Wurm": "Creature",
            "Tinder Wall": "Creature", "An-Havva Inn": "Sorcery",
            "Crumble": "Instant", "Desert Twister": "Sorcery",
            "Giant Growth": "Instant", "Hurricane": "Sorcery",
            "Lure": "Enchantment", "Primal Order": "Enchantment",
            "Regrowth": "Sorcery", "Stampede": "Instant",
            "Tranquility": "Sorcery", "Lightning Bolt": "Instant",
            "Wheel of Fortune": "Sorcery", "Feldon's Cane": "Artifact",
            "Sol Ring": "Artifact", "Zuran Orb": "Artifact",
            "Pendelhaven": "Land", "Strip Mine": "Land", "Taiga": "Land",
            "Lifeforce": "Enchantment", "Sandstorm": "Instant",
            "Shatterstorm": "Sorcery", "Tsunami": "Sorcery",
        ],
        cardManaCosts: [
            "Autumn Willow": "{4}{G}{G}", "Erhnam Djinn": "{3}{G}",
            "Force of Nature": "{2}{G}{G}{G}{G}", "Fyndhorn Elder": "{2}{G}",
            "Fyndhorn Elves": "{G}", "Hungry Mist": "{2}{G}{G}",
            "Johtull Wurm": "{5}{G}", "Killer Bees": "{1}{G}{G}",
            "Llanowar Elves": "{G}", "Scaled Wurm": "{7}{G}",
            "Tinder Wall": "{G}", "An-Havva Inn": "{1}{G}{G}",
            "Crumble": "{G}", "Desert Twister": "{4}{G}{G}",
            "Giant Growth": "{G}", "Hurricane": "{X}{G}",
            "Lure": "{1}{G}", "Primal Order": "{2}{G}{G}",
            "Regrowth": "{1}{G}", "Stampede": "{1}{G}{G}",
            "Tranquility": "{1}{G}", "Lightning Bolt": "{R}",
            "Wheel of Fortune": "{2}{R}", "Feldon's Cane": "{1}",
            "Sol Ring": "{1}", "Zuran Orb": "{0}",
            "Lifeforce": "{G}{G}", "Sandstorm": "{G}",
            "Shatterstorm": "{2}{R}{R}", "Tsunami": "{3}{G}",
        ],
        source: "InQuest Magazine Issue #9, January 1996. \"It's Easy Being Green.\"",
        description: "Mono-green ramp with a red splash. Seven mana elves power out turn-3 fatties like Scaled Wurm and Erhnam Djinn. Tinder Wall provides both acceleration and red mana for Lightning Bolt and Wheel of Fortune. Lure + Giant Growth for lethal alpha strikes, Stampede for the swarm finish."
    )

    // MARK: - Issue #16 (August 1996) — Dastardly Denial Deck

    static let dastardlyDenial = ClassicArchetype(
        id: "inquest-dastardly-denial",
        name: "#16 · Dastardly Denial Deck",
        era: "1996",
        format: "Type II",
        mainboard: [
            "Arcane Denial": 4,
            "Browse": 1,
            "Counterspell": 4,
            "Force of Will": 3,
            "Library of Lat-Nam": 2,
            "Storm Elemental": 2,
            "Zuran Spellcaster": 3,
            "Disenchant": 4,
            "Exile": 2,
            "Swords to Plowshares": 4,
            "Blinking Spirit": 3,
            "Ivory Gargoyle": 3,
            "Helm of Obedience": 4,
            "Icy Manipulator": 3,
            "Sol Grail": 2,
            "Zuran Orb": 1,
            "Adarkar Wastes": 4,
            "Island": 14,
            "Kjeldoran Outpost": 1,
            "Plains": 10,
            "Soldevi Excavations": 1,
        ],
        sideboard: [
            "Circle of Protection: Green": 2,
            "Circle of Protection: Red": 3,
            "Diminishing Returns": 1,
            "Glacial Chasm": 2,
            "Jester's Cap": 1,
            "Lodestone Bauble": 3,
            "Reprisal": 3,
        ],
        cardSets: [
            "Arcane Denial": "ALL", "Browse": "ALL", "Counterspell": "ICE",
            "Force of Will": "ALL", "Library of Lat-Nam": "ALL",
            "Storm Elemental": "ALL", "Zuran Spellcaster": "ICE",
            "Disenchant": "ICE", "Exile": "ALL", "Swords to Plowshares": "ICE",
            "Blinking Spirit": "ICE", "Ivory Gargoyle": "ALL",
            "Helm of Obedience": "ALL", "Icy Manipulator": "ICE",
            "Sol Grail": "ALL", "Zuran Orb": "ICE",
            "Adarkar Wastes": "ICE", "Kjeldoran Outpost": "ALL",
            "Soldevi Excavations": "ALL",
            "Island": "ICE", "Plains": "ICE",
            "Circle of Protection: Green": "ICE", "Circle of Protection: Red": "ICE",
            "Diminishing Returns": "ALL", "Glacial Chasm": "ICE",
            "Jester's Cap": "ICE", "Lodestone Bauble": "ALL", "Reprisal": "ALL",
        ],
        cardTypes: [
            "Arcane Denial": "Instant", "Browse": "Enchantment",
            "Counterspell": "Instant", "Force of Will": "Instant",
            "Library of Lat-Nam": "Sorcery", "Storm Elemental": "Creature",
            "Zuran Spellcaster": "Creature", "Disenchant": "Instant",
            "Exile": "Sorcery", "Swords to Plowshares": "Instant",
            "Blinking Spirit": "Creature", "Ivory Gargoyle": "Creature",
            "Helm of Obedience": "Artifact", "Icy Manipulator": "Artifact",
            "Sol Grail": "Artifact", "Zuran Orb": "Artifact",
            "Adarkar Wastes": "Land", "Kjeldoran Outpost": "Land",
            "Soldevi Excavations": "Land",
            "Circle of Protection: Green": "Enchantment",
            "Circle of Protection: Red": "Enchantment",
            "Diminishing Returns": "Sorcery", "Glacial Chasm": "Land",
            "Jester's Cap": "Artifact", "Lodestone Bauble": "Artifact",
            "Reprisal": "Instant",
        ],
        cardManaCosts: [
            "Arcane Denial": "{1}{U}", "Browse": "{2}{U}{U}",
            "Counterspell": "{U}{U}", "Force of Will": "{3}{U}{U}",
            "Library of Lat-Nam": "{4}{U}", "Storm Elemental": "{5}{U}",
            "Zuran Spellcaster": "{2}{U}", "Disenchant": "{1}{W}",
            "Exile": "{2}{W}", "Swords to Plowshares": "{W}",
            "Blinking Spirit": "{3}{W}", "Ivory Gargoyle": "{4}{W}",
            "Helm of Obedience": "{4}", "Icy Manipulator": "{4}",
            "Sol Grail": "{3}", "Zuran Orb": "{0}",
            "Circle of Protection: Green": "{1}{W}",
            "Circle of Protection: Red": "{1}{W}",
            "Diminishing Returns": "{2}{U}{U}",
            "Jester's Cap": "{4}", "Lodestone Bauble": "{0}",
            "Reprisal": "{1}{W}",
        ],
        source: "InQuest Magazine Issue #16, August 1996. \"Mother, May I?\" by Jeff Hannes.",
        description: "Blue/White permission control — the article title asks 'Mother, May I?' because opponents need permission for everything. Counterspells and Force of Will lock down threats, Helm of Obedience mills the opponent out, and Zuran Spellcasters ping for damage. Icy Manipulators and Blinking Spirit provide inevitability."
    )

    // MARK: - Issue #20 (December 1996) — Deepwater Death

    static let deepwaterDeath = ClassicArchetype(
        id: "inquest-deepwater-death",
        name: "#20 · Deepwater Death",
        era: "1996",
        format: "Mirage",
        mainboard: [
            "Amber Prison": 2,
            "Withering Boon": 2,
            "Bone Harvest": 2,
            "Cadaverous Knight": 3,
            "Catacomb Dragon": 1,
            "Dark Banishing": 2,
            "Dark Ritual": 4,
            "Drain Life": 4,
            "Mystical Tutor": 1,
            "Power Sink": 3,
            "Taniwha": 2,
            "Benthic Djinn": 3,
            "Sealed Fate": 2,
            "Unfulfilled Desires": 2,
            "Sewer Rats": 2,
            "Skulking Ghost": 3,
            "Island": 8,
            "Swamp": 14,
        ],
        sideboard: [
            "Bone Harvest": 1,
            "Cerulean Wyvern": 1,
            "Cursed Totem": 1,
            "Dark Banishing": 2,
            "Mind Bend": 2,
            "Mind Harness": 2,
            "Reign of Terror": 2,
            "Shimmer": 2,
            "Soul Rend": 2,
        ],
        cardSets: [
            "Amber Prison": "MIR", "Withering Boon": "MIR",
            "Bone Harvest": "MIR", "Cadaverous Knight": "MIR",
            "Catacomb Dragon": "MIR", "Dark Banishing": "MIR",
            "Dark Ritual": "MIR", "Drain Life": "MIR",
            "Mystical Tutor": "MIR", "Power Sink": "MIR", "Taniwha": "MIR",
            "Benthic Djinn": "MIR", "Sealed Fate": "MIR",
            "Unfulfilled Desires": "MIR", "Sewer Rats": "MIR",
            "Skulking Ghost": "MIR",
            "Island": "MIR", "Swamp": "MIR",
            "Cerulean Wyvern": "MIR", "Cursed Totem": "MIR",
            "Mind Bend": "MIR", "Mind Harness": "MIR",
            "Reign of Terror": "MIR", "Shimmer": "MIR", "Soul Rend": "MIR",
        ],
        cardTypes: [
            "Amber Prison": "Artifact", "Withering Boon": "Instant",
            "Bone Harvest": "Instant", "Cadaverous Knight": "Creature",
            "Catacomb Dragon": "Creature", "Dark Banishing": "Instant",
            "Dark Ritual": "Instant", "Drain Life": "Sorcery",
            "Mystical Tutor": "Instant", "Power Sink": "Instant",
            "Taniwha": "Creature", "Benthic Djinn": "Creature",
            "Sealed Fate": "Sorcery", "Unfulfilled Desires": "Enchantment",
            "Sewer Rats": "Creature", "Skulking Ghost": "Creature",
            "Cerulean Wyvern": "Creature", "Cursed Totem": "Artifact",
            "Mind Bend": "Instant", "Mind Harness": "Enchantment",
            "Reign of Terror": "Sorcery", "Shimmer": "Enchantment",
            "Soul Rend": "Instant",
        ],
        cardManaCosts: [
            "Amber Prison": "{4}", "Withering Boon": "{1}{B}",
            "Bone Harvest": "{2}{B}", "Cadaverous Knight": "{2}{B}",
            "Catacomb Dragon": "{4}{B}{B}", "Dark Banishing": "{2}{B}",
            "Dark Ritual": "{B}", "Drain Life": "{X}{1}{B}",
            "Mystical Tutor": "{U}", "Power Sink": "{X}{U}",
            "Taniwha": "{3}{U}{U}", "Benthic Djinn": "{2}{U}{B}",
            "Sealed Fate": "{X}{U}{B}", "Unfulfilled Desires": "{1}{U}{B}",
            "Sewer Rats": "{B}", "Skulking Ghost": "{1}{B}",
            "Cerulean Wyvern": "{4}{U}", "Cursed Totem": "{2}",
            "Mind Bend": "{U}", "Mind Harness": "{U}",
            "Reign of Terror": "{3}{B}{B}", "Shimmer": "{2}{U}{U}",
            "Soul Rend": "{1}{B}",
        ],
        source: "InQuest Magazine Issue #20, December 1996.",
        description: "Blue/Black Mirage-block control. Taniwha phases out every other turn but hits for 7/7 trample, Benthic Djinn provides efficient 5/6 beatdown, and Catacomb Dragon shrinks blockers. Amber Prison locks down threats, Unfulfilled Desires filters draws, and Drain Life doubles as removal and lifegain."
    )

    // MARK: - Issue #22 (February 1997) — The Null Void

    static let nullVoid = ClassicArchetype(
        id: "inquest-null-void",
        name: "#22 · The Null Void",
        era: "1997",
        format: "Type II",
        mainboard: [
            "Fellwar Stone": 4,
            "Fire Diamond": 2,
            "Fountain of Youth": 2,
            "Glasses of Urza": 1,
            "Jayemdae Tome": 1,
            "Lodestone Bauble": 1,
            "Marble Diamond": 2,
            "Serrated Arrows": 1,
            "Winter Orb": 2,
            "Disintegrate": 1,
            "Earthquake": 1,
            "Hammer of Bogardan": 1,
            "Incinerate": 1,
            "Kaervek's Torch": 1,
            "Land's Edge": 1,
            "Lightning Bolt": 1,
            "Pillage": 2,
            "Power Surge": 2,
            "Wildfire Emissary": 2,
            "Armageddon": 1,
            "Divine Offering": 2,
            "Enlightened Tutor": 3,
            "Null Chamber": 3,
            "Pacifism": 2,
            "Swords to Plowshares": 1,
            "Wrath of God": 2,
            "Kjeldoran Outpost": 2,
            "Mountain": 6,
            "Plains": 10,
            "Thawing Glaciers": 1,
        ],
        sideboard: [
            "Circle of Protection: Black": 2,
            "Circle of Protection: Green": 2,
            "Circle of Protection: Red": 2,
            "Disenchant": 2,
            "Karma": 2,
            "Meekstone": 2,
            "Red Elemental Blast": 2,
            "Serrated Arrows": 1,
        ],
        cardSets: [
            "Fellwar Stone": "DRK", "Fire Diamond": "MIR", "Fountain of Youth": "DRK",
            "Glasses of Urza": "LEA", "Jayemdae Tome": "LEA", "Lodestone Bauble": "ALL",
            "Marble Diamond": "MIR", "Serrated Arrows": "HML", "Winter Orb": "LEA",
            "Disintegrate": "LEA", "Earthquake": "LEA", "Hammer of Bogardan": "MIR",
            "Incinerate": "MIR", "Kaervek's Torch": "VIS", "Land's Edge": "LEG",
            "Lightning Bolt": "LEA", "Pillage": "ALL", "Power Surge": "LEA",
            "Wildfire Emissary": "MIR", "Armageddon": "LEA", "Divine Offering": "LEA",
            "Enlightened Tutor": "MIR", "Null Chamber": "MIR", "Pacifism": "MIR",
            "Swords to Plowshares": "ICE", "Wrath of God": "LEA",
            "Thawing Glaciers": "ALL", "Kjeldoran Outpost": "ALL",
            "Mountain": "MIR", "Plains": "MIR",
            "Circle of Protection: Black": "ICE", "Circle of Protection: Green": "ICE",
            "Circle of Protection: Red": "ICE", "Disenchant": "MIR",
            "Karma": "LEA", "Meekstone": "LEA", "Red Elemental Blast": "LEA",
        ],
        cardTypes: [
            "Fellwar Stone": "Artifact", "Fire Diamond": "Artifact",
            "Fountain of Youth": "Artifact", "Glasses of Urza": "Artifact",
            "Jayemdae Tome": "Artifact", "Lodestone Bauble": "Artifact",
            "Marble Diamond": "Artifact", "Serrated Arrows": "Artifact",
            "Winter Orb": "Artifact", "Disintegrate": "Sorcery",
            "Earthquake": "Sorcery", "Hammer of Bogardan": "Sorcery",
            "Incinerate": "Instant", "Kaervek's Torch": "Sorcery",
            "Land's Edge": "Enchantment", "Lightning Bolt": "Instant",
            "Pillage": "Sorcery", "Power Surge": "Enchantment",
            "Wildfire Emissary": "Creature", "Armageddon": "Sorcery",
            "Divine Offering": "Instant", "Enlightened Tutor": "Instant",
            "Null Chamber": "Artifact", "Pacifism": "Enchantment",
            "Swords to Plowshares": "Instant", "Wrath of God": "Sorcery",
            "Kjeldoran Outpost": "Land", "Thawing Glaciers": "Land",
            "Circle of Protection: Black": "Enchantment",
            "Circle of Protection: Green": "Enchantment",
            "Circle of Protection: Red": "Enchantment",
            "Disenchant": "Instant", "Karma": "Enchantment",
            "Meekstone": "Artifact", "Red Elemental Blast": "Instant",
        ],
        cardManaCosts: [
            "Fellwar Stone": "{2}", "Fire Diamond": "{2}",
            "Fountain of Youth": "{0}", "Glasses of Urza": "{1}",
            "Jayemdae Tome": "{4}", "Lodestone Bauble": "{0}",
            "Marble Diamond": "{2}", "Serrated Arrows": "{4}",
            "Winter Orb": "{2}", "Disintegrate": "{X}{R}",
            "Earthquake": "{X}{R}", "Hammer of Bogardan": "{1}{R}{R}",
            "Incinerate": "{1}{R}", "Kaervek's Torch": "{X}{R}",
            "Land's Edge": "{1}{R}{R}", "Lightning Bolt": "{R}",
            "Pillage": "{1}{R}{R}", "Power Surge": "{R}{R}",
            "Wildfire Emissary": "{3}{R}", "Armageddon": "{3}{W}",
            "Divine Offering": "{1}{W}", "Enlightened Tutor": "{W}",
            "Null Chamber": "{3}{W}", "Pacifism": "{1}{W}",
            "Swords to Plowshares": "{W}", "Wrath of God": "{2}{W}{W}",
            "Circle of Protection: Black": "{1}{W}",
            "Circle of Protection: Green": "{1}{W}",
            "Circle of Protection: Red": "{1}{W}",
            "Disenchant": "{1}{W}", "Karma": "{2}{W}{W}",
            "Meekstone": "{1}", "Red Elemental Blast": "{R}",
        ],
        source: "InQuest Magazine Issue #22, February 1997.",
        description: "White/Red prison control. Null Chamber names key opponent cards to lock them out, Winter Orb slows their mana while your mana rocks keep flowing, Enlightened Tutor finds the right answer for any situation. Power Surge punishes tapped lands, Land's Edge converts excess lands into damage, and Armageddon seals the game after deploying your artifact mana base."
    )

    // MARK: - Issue #23 (March 1997) — Fire and Ice

    static let fireAndIce = ClassicArchetype(
        id: "inquest-fire-and-ice",
        name: "#23 · Fire and Ice",
        era: "1997",
        format: "Type II",
        mainboard: [
            "Nevinyrral's Disk": 2,
            "Mahamoti Djinn": 2,
            "Mist Dragon": 2,
            "Arcane Denial": 4,
            "Control Magic": 2,
            "Counterspell": 4,
            "Force of Will": 4,
            "Recall": 1,
            "Wildfire Emissary": 3,
            "Hammer of Bogardan": 2,
            "Incinerate": 3,
            "Kaervek's Torch": 1,
            "Lightning Bolt": 4,
            "Pillage": 2,
            "Island": 12,
            "Mountain": 10,
            "Thawing Glaciers": 2,
        ],
        sideboard: [
            "Disrupting Scepter": 2,
            "Energy Flux": 2,
            "Feldon's Cane": 1,
            "Mind Harness": 2,
            "Nevinyrral's Disk": 2,
            "Pillage": 1,
            "Pyrokinesis": 1,
            "Red Elemental Blast": 2,
            "Tidal Wave": 2,
        ],
        cardSets: [
            "Nevinyrral's Disk": "ICE", "Mahamoti Djinn": "LEA", "Mist Dragon": "MIR",
            "Arcane Denial": "ALL", "Control Magic": "LEA", "Counterspell": "ICE",
            "Force of Will": "ALL", "Recall": "LEG",
            "Wildfire Emissary": "MIR", "Hammer of Bogardan": "MIR",
            "Incinerate": "MIR", "Kaervek's Torch": "VIS", "Lightning Bolt": "LEA",
            "Pillage": "ALL", "Thawing Glaciers": "ALL",
            "Island": "5ED", "Mountain": "5ED",
            "Disrupting Scepter": "LEA", "Energy Flux": "LEA", "Feldon's Cane": "ATQ",
            "Mind Harness": "MIR", "Pyrokinesis": "ALL", "Red Elemental Blast": "LEA",
            "Tidal Wave": "ALL",
        ],
        cardTypes: [
            "Nevinyrral's Disk": "Artifact", "Mahamoti Djinn": "Creature",
            "Mist Dragon": "Creature", "Arcane Denial": "Instant",
            "Control Magic": "Enchantment", "Counterspell": "Instant",
            "Force of Will": "Instant", "Recall": "Sorcery",
            "Wildfire Emissary": "Creature", "Hammer of Bogardan": "Sorcery",
            "Incinerate": "Instant", "Kaervek's Torch": "Sorcery",
            "Lightning Bolt": "Instant", "Pillage": "Sorcery",
            "Thawing Glaciers": "Land",
            "Disrupting Scepter": "Artifact", "Energy Flux": "Enchantment",
            "Feldon's Cane": "Artifact", "Mind Harness": "Enchantment",
            "Pyrokinesis": "Instant", "Red Elemental Blast": "Instant",
            "Tidal Wave": "Instant",
        ],
        cardManaCosts: [
            "Nevinyrral's Disk": "{4}", "Mahamoti Djinn": "{4}{U}{U}",
            "Mist Dragon": "{4}{U}{U}", "Arcane Denial": "{1}{U}",
            "Control Magic": "{2}{U}{U}", "Counterspell": "{U}{U}",
            "Force of Will": "{3}{U}{U}", "Recall": "{X}{X}{U}",
            "Wildfire Emissary": "{3}{R}", "Hammer of Bogardan": "{1}{R}{R}",
            "Incinerate": "{1}{R}", "Kaervek's Torch": "{X}{R}",
            "Lightning Bolt": "{R}", "Pillage": "{1}{R}{R}",
            "Disrupting Scepter": "{3}", "Energy Flux": "{2}{U}",
            "Feldon's Cane": "{1}", "Mind Harness": "{U}",
            "Pyrokinesis": "{4}{R}{R}", "Red Elemental Blast": "{R}",
            "Tidal Wave": "{2}{U}",
        ],
        source: "InQuest Magazine Issue #23, March 1997.",
        description: "Blue/Red counter-burn control. Force of Will and Counterspell protect your board while Lightning Bolt, Incinerate, and Hammer of Bogardan burn the opponent out. Mahamoti Djinn and Mist Dragon close games in the air, Nevinyrral's Disk resets the board when needed, and Thawing Glaciers ensures you never miss a land drop."
    )

    // MARK: - Issue #24 (April 1997) — The Karate Deck

    static let karateDeck = ClassicArchetype(
        id: "inquest-karate-deck",
        name: "#24 · The Karate Deck",
        era: "1997",
        format: "Mirage/Visions",
        mainboard: [
            "Aku Djinn": 2,
            "Dark Ritual": 4,
            "Nekrataal": 4,
            "Pillar Tombs of Aku": 2,
            "Delirium": 4,
            "Emberwilde Djinn": 2,
            "Hammer of Bogardan": 2,
            "Incinerate": 4,
            "Kaervek's Purge": 4,
            "Kaervek's Torch": 3,
            "Torrent of Lava": 1,
            "Wildfire Emissary": 4,
            "Mountain": 12,
            "Swamp": 12,
        ],
        sideboard: [
            "Ebony Charm": 2,
            "Ekundu Cyclops": 3,
            "Emberwilde Djinn": 2,
            "Hammer of Bogardan": 2,
            "Kaervek's Torch": 1,
            "Pillar Tombs of Aku": 2,
            "Shadow Guildmage": 2,
            "Torrent of Lava": 1,
        ],
        cardSets: [
            "Aku Djinn": "VIS", "Dark Ritual": "MIR", "Nekrataal": "VIS",
            "Pillar Tombs of Aku": "VIS", "Delirium": "MIR",
            "Emberwilde Djinn": "MIR", "Hammer of Bogardan": "MIR",
            "Incinerate": "MIR", "Kaervek's Purge": "VIS",
            "Kaervek's Torch": "VIS", "Torrent of Lava": "MIR",
            "Wildfire Emissary": "MIR",
            "Ebony Charm": "MIR", "Ekundu Cyclops": "MIR",
            "Shadow Guildmage": "MIR",
            "Mountain": "5ED", "Swamp": "5ED",
        ],
        cardTypes: [
            "Aku Djinn": "Creature", "Dark Ritual": "Instant",
            "Nekrataal": "Creature", "Pillar Tombs of Aku": "Enchantment",
            "Delirium": "Instant", "Emberwilde Djinn": "Creature",
            "Hammer of Bogardan": "Sorcery", "Incinerate": "Instant",
            "Kaervek's Purge": "Sorcery", "Kaervek's Torch": "Sorcery",
            "Torrent of Lava": "Sorcery", "Wildfire Emissary": "Creature",
            "Ebony Charm": "Instant", "Ekundu Cyclops": "Creature",
            "Shadow Guildmage": "Creature",
        ],
        cardManaCosts: [
            "Aku Djinn": "{3}{B}{B}", "Dark Ritual": "{B}",
            "Nekrataal": "{2}{B}{B}", "Pillar Tombs of Aku": "{1}{B}",
            "Delirium": "{1}{B}{R}", "Emberwilde Djinn": "{2}{R}{R}",
            "Hammer of Bogardan": "{1}{R}{R}", "Incinerate": "{1}{R}",
            "Kaervek's Purge": "{X}{B}{R}", "Kaervek's Torch": "{X}{R}",
            "Torrent of Lava": "{X}{R}{R}", "Wildfire Emissary": "{3}{R}",
            "Ebony Charm": "{B}", "Ekundu Cyclops": "{2}{R}",
            "Shadow Guildmage": "{B}",
        ],
        source: "InQuest Magazine Issue #24, April 1997. \"The Bigger They Are...\" by Alex Shvartsman.",
        description: "Black/Red creature-punisher for Mirage/Visions format. Kaervek's Purge kills creatures and deals their power to the controller. Delirium taps creatures and reflects their power as damage. Emberwilde Djinn is a 5/4 that bounces between players, setting up devastating Delirium/Purge combos."
    )

    // MARK: - Issue #26 (June 1997) — Don't Eat My Lunch

    static let dontEatMyLunch = ClassicArchetype(
        id: "inquest-dont-eat-my-lunch",
        name: "#26 · Don't Eat My Lunch",
        era: "1997",
        format: "Type 1.5",
        mainboard: [
            "Serendib Efreet": 4,
            "Browse": 2,
            "Control Magic": 2,
            "Counterspell": 2,
            "Force of Will": 2,
            "Mana Drain": 4,
            "Erhnam Djinn": 3,
            "Disenchant": 3,
            "Spirit Link": 3,
            "Swords to Plowshares": 4,
            "Wrath of God": 1,
            "Island": 6,
            "Forest": 1,
            "Kjeldoran Outpost": 3,
            "Mishra's Factory": 3,
            "Plains": 4,
            "Savannah": 4,
            "Thawing Glaciers": 2,
            "Tropical Island": 3,
            "Tundra": 4,
        ],
        sideboard: [
            "Circle of Protection: Red": 3,
            "Disenchant": 1,
            "Divine Offering": 2,
            "Hydroblast": 3,
            "Mind Harness": 2,
            "Political Trickery": 3,
            "Wrath of God": 1,
        ],
        cardSets: [
            "Serendib Efreet": "ARN", "Browse": "ALL", "Control Magic": "LEA",
            "Counterspell": "ICE", "Force of Will": "ALL", "Mana Drain": "LEG",
            "Erhnam Djinn": "ARN", "Disenchant": "ICE", "Spirit Link": "LEA",
            "Swords to Plowshares": "ICE", "Wrath of God": "LEA",
            "Kjeldoran Outpost": "ALL", "Mishra's Factory": "ATQ", "Savannah": "LEA", "Thawing Glaciers": "ALL",
            "Tropical Island": "LEA", "Tundra": "LEA",
            "Island": "5ED", "Forest": "5ED", "Plains": "5ED",
            "Circle of Protection: Red": "ICE", "Divine Offering": "LEA",
            "Hydroblast": "ICE", "Mind Harness": "MIR", "Political Trickery": "MIR",
        ],
        cardTypes: [
            "Serendib Efreet": "Creature", "Browse": "Enchantment",
            "Control Magic": "Enchantment", "Counterspell": "Instant",
            "Force of Will": "Instant", "Mana Drain": "Instant",
            "Erhnam Djinn": "Creature", "Disenchant": "Instant",
            "Spirit Link": "Enchantment", "Swords to Plowshares": "Instant",
            "Wrath of God": "Sorcery",
            "Kjeldoran Outpost": "Land", "Mishra's Factory": "Land",
            "Savannah": "Land", "Thawing Glaciers": "Land",
            "Tropical Island": "Land", "Tundra": "Land",
            "Circle of Protection: Red": "Enchantment",
            "Divine Offering": "Instant", "Hydroblast": "Instant",
            "Mind Harness": "Enchantment", "Political Trickery": "Sorcery",
        ],
        cardManaCosts: [
            "Serendib Efreet": "{2}{U}", "Browse": "{2}{U}{U}",
            "Control Magic": "{2}{U}{U}", "Counterspell": "{U}{U}",
            "Force of Will": "{3}{U}{U}", "Mana Drain": "{U}{U}",
            "Erhnam Djinn": "{3}{G}", "Disenchant": "{1}{W}",
            "Spirit Link": "{W}", "Swords to Plowshares": "{W}",
            "Wrath of God": "{2}{W}{W}",
            "Circle of Protection: Red": "{1}{W}",
            "Divine Offering": "{1}{W}", "Hydroblast": "{U}",
            "Mind Harness": "{U}", "Political Trickery": "{2}{U}",
        ],
        source: "InQuest Magazine Issue #26, June 1997. \"King Suleiman's Nightmare\" by Mark Justice.",
        description: "Bant (UWG) midrange control by 1995 US National Champion Mark Justice. Serendib Efreet and Erhnam Djinn provide efficient beatdown, Spirit Link neutralizes opposing creatures and gains life on your own Efreets. Mana Drain fuels big plays, Kjeldoran Outpost generates tokens for the long game."
    )

    // MARK: - Issue #33 (January 1998) — The Ultimate 187

    static let ultimate187 = ClassicArchetype(
        id: "inquest-ultimate-187",
        name: "#33 · The Ultimate 187",
        era: "1998",
        format: "Type 1.5",
        mainboard: [
            "Barbed Sextant": 2,
            "Black Knight": 3,
            "Knight of Stromgald": 4,
            "Nekrataal": 4,
            "Shadow Guildmage": 4,
            "Disturbed Burial": 3,
            "Vampiric Tutor": 2,
            "Man-o'-War": 4,
            "Ophidian": 4,
            "Capsize": 2,
            "Whim of Volrath": 2,
            "Uktabi Orangutan": 3,
            "Cloudchaser Eagle": 3,
            "Brushland": 1,
            "City of Brass": 4,
            "Island": 4,
            "Swamp": 8,
            "Underground River": 4,
            "Undiscovered Paradise": 2,
        ],
        sideboard: [
            "Circle of Protection: Red": 2,
            "Cloudchaser Eagle": 1,
            "Fevered Convulsions": 4,
            "Hydroblast": 2,
            "Perish": 1,
            "Pyroblast": 2,
            "Scragnoth": 1,
            "Spinning Darkness": 2,
        ],
        cardSets: [
            "Barbed Sextant": "ICE", "Black Knight": "4ED",
            "Knight of Stromgald": "ICE", "Nekrataal": "VIS",
            "Shadow Guildmage": "MIR", "Disturbed Burial": "TMP",
            "Vampiric Tutor": "VIS", "Man-o'-War": "VIS", "Ophidian": "WTH",
            "Capsize": "TMP", "Whim of Volrath": "TMP",
            "Uktabi Orangutan": "VIS", "Cloudchaser Eagle": "TMP",
            "Brushland": "ICE", "City of Brass": "5ED",
            "Underground River": "ICE", "Undiscovered Paradise": "VIS",
            "Island": "TMP", "Swamp": "TMP",
            "Circle of Protection: Red": "ICE", "Fevered Convulsions": "VIS",
            "Hydroblast": "ICE", "Perish": "TMP", "Pyroblast": "ICE",
            "Scragnoth": "TMP", "Spinning Darkness": "WTH",
        ],
        cardTypes: [
            "Barbed Sextant": "Artifact", "Black Knight": "Creature",
            "Knight of Stromgald": "Creature", "Nekrataal": "Creature",
            "Shadow Guildmage": "Creature", "Disturbed Burial": "Sorcery",
            "Vampiric Tutor": "Instant", "Man-o'-War": "Creature",
            "Ophidian": "Creature", "Capsize": "Instant",
            "Whim of Volrath": "Instant", "Uktabi Orangutan": "Creature",
            "Cloudchaser Eagle": "Creature",
            "Brushland": "Land", "City of Brass": "Land",
            "Underground River": "Land", "Undiscovered Paradise": "Land",
            "Circle of Protection: Red": "Enchantment",
            "Fevered Convulsions": "Enchantment", "Hydroblast": "Instant",
            "Perish": "Sorcery", "Pyroblast": "Instant",
            "Scragnoth": "Creature", "Spinning Darkness": "Instant",
        ],
        cardManaCosts: [
            "Barbed Sextant": "{1}", "Black Knight": "{B}{B}",
            "Knight of Stromgald": "{B}{B}", "Nekrataal": "{2}{B}{B}",
            "Shadow Guildmage": "{B}", "Disturbed Burial": "{1}{B}",
            "Vampiric Tutor": "{B}", "Man-o'-War": "{2}{U}",
            "Ophidian": "{2}{U}", "Capsize": "{1}{U}{U}",
            "Whim of Volrath": "{U}", "Uktabi Orangutan": "{2}{G}",
            "Cloudchaser Eagle": "{3}{W}",
            "Circle of Protection: Red": "{1}{W}",
            "Fevered Convulsions": "{B}{B}", "Hydroblast": "{U}",
            "Perish": "{1}{B}{B}", "Pyroblast": "{R}",
            "Scragnoth": "{4}{G}", "Spinning Darkness": "{4}{B}{B}",
        ],
        source: "InQuest Magazine Issue #33, January 1998. \"The Ultimate 187\" by Alex Shvartsman.",
        description: "Five-color '187' deck — named after the police code for homicide. Every creature kills something when it enters play: Nekrataal destroys creatures, Man-o'-War bounces them, Uktabi Orangutan smashes artifacts, Cloudchaser Eagle removes enchantments. Disturbed Burial and Ophidian provide card advantage to keep the 187s coming."
    )

    // MARK: - Issue #41 (September 1998) — Player Hater's Paradise

    static let playerHatersParadise = ClassicArchetype(
        id: "inquest-player-haters-paradise",
        name: "#41 · Player Hater's Paradise",
        era: "1998",
        format: "Type II",
        mainboard: [
            "Cursed Scroll": 4,
            "Black Knight": 4,
            "Carnophage": 4,
            "Dauthi Slayer": 4,
            "Erg Raiders": 4,
            "Bad Moon": 4,
            "Dark Ritual": 4,
            "Hatred": 4,
            "Mox Diamond": 4,
            "Sarcomancy": 4,
            "Unholy Strength": 4,
            "Swamp": 16,
        ],
        sideboard: [
            "Coercion": 4,
            "Diabolic Edict": 3,
            "Spinning Darkness": 4,
            "Perish": 2,
            "Wasteland": 2,
        ],
        cardSets: [
            "Cursed Scroll": "TMP", "Black Knight": "LEA", "Carnophage": "EXO",
            "Dauthi Slayer": "TMP", "Erg Raiders": "ARN", "Bad Moon": "LEA",
            "Dark Ritual": "LEA", "Hatred": "EXO", "Mox Diamond": "STH",
            "Sarcomancy": "TMP", "Unholy Strength": "LEA",
            "Swamp": "TMP",
            "Coercion": "VIS", "Diabolic Edict": "TMP", "Spinning Darkness": "WTH",
            "Perish": "TMP", "Wasteland": "TMP",
        ],
        cardTypes: [
            "Cursed Scroll": "Artifact", "Black Knight": "Creature",
            "Carnophage": "Creature", "Dauthi Slayer": "Creature",
            "Erg Raiders": "Creature", "Bad Moon": "Enchantment",
            "Dark Ritual": "Instant", "Hatred": "Instant",
            "Mox Diamond": "Artifact", "Sarcomancy": "Enchantment",
            "Unholy Strength": "Enchantment",
            "Coercion": "Sorcery", "Diabolic Edict": "Instant",
            "Spinning Darkness": "Instant", "Perish": "Sorcery",
            "Wasteland": "Land",
        ],
        cardManaCosts: [
            "Cursed Scroll": "{1}", "Black Knight": "{B}{B}",
            "Carnophage": "{B}", "Dauthi Slayer": "{B}{B}",
            "Erg Raiders": "{1}{B}", "Bad Moon": "{1}{B}",
            "Dark Ritual": "{B}", "Hatred": "{3}{B}{B}",
            "Mox Diamond": "{0}", "Sarcomancy": "{B}",
            "Unholy Strength": "{B}",
            "Coercion": "{2}{B}", "Diabolic Edict": "{1}{B}",
            "Spinning Darkness": "{4}{B}{B}", "Perish": "{1}{B}{B}",
        ],
        source: "InQuest Magazine Issue #41, September 1998.",
        description: "Mono-Black Suicide — the fastest aggro deck in Type II. Every non-land card costs 0-3 mana. Dark Ritual into Carnophage + Sarcomancy on turn 1, swing for 4 on turn 2, then Hatred for lethal. Mox Diamond enables explosive starts, Bad Moon pumps the team, Cursed Scroll picks off blockers."
    )

    // MARK: - Shadowslayer (~1997, Tempest era)

    static let shadowslayer = ClassicArchetype(
        id: "inquest-shadowslayer",
        name: "Shadowslayer",
        era: "1997",
        format: "Type II",
        mainboard: [
            "Blood Frenzy": 3,
            "Fireslinger": 4,
            "Goblin Bombardment": 2,
            "Kindle": 4,
            "Lightning Blast": 3,
            "Mogg Conscripts": 4,
            "Rathi Dragon": 2,
            "Rolling Thunder": 1,
            "Scorched Earth": 1,
            "Disenchant": 1,
            "Field of Souls": 1,
            "Knight of Dawn": 2,
            "Soltari Crusader": 1,
            "Soltari Foot Soldier": 4,
            "Soltari Monk": 3,
            "Soltari Priest": 3,
            "Mountain": 12,
            "Plains": 7,
            "Reflecting Pool": 2,
        ],
        cardSets: [
            "Blood Frenzy": "TMP", "Fireslinger": "TMP",
            "Goblin Bombardment": "TMP", "Kindle": "TMP",
            "Lightning Blast": "TMP", "Mogg Conscripts": "TMP",
            "Rathi Dragon": "TMP", "Rolling Thunder": "TMP",
            "Scorched Earth": "TMP", "Disenchant": "TMP",
            "Field of Souls": "TMP", "Knight of Dawn": "TMP",
            "Soltari Crusader": "TMP", "Soltari Foot Soldier": "TMP",
            "Soltari Monk": "TMP", "Soltari Priest": "TMP",
            "Reflecting Pool": "TMP",
            "Mountain": "5ED", "Plains": "5ED",
        ],
        cardTypes: [
            "Blood Frenzy": "Instant", "Fireslinger": "Creature",
            "Goblin Bombardment": "Enchantment", "Kindle": "Instant",
            "Lightning Blast": "Instant", "Mogg Conscripts": "Creature",
            "Rathi Dragon": "Creature", "Rolling Thunder": "Sorcery",
            "Scorched Earth": "Sorcery", "Disenchant": "Instant",
            "Field of Souls": "Enchantment", "Knight of Dawn": "Creature",
            "Soltari Crusader": "Creature", "Soltari Foot Soldier": "Creature",
            "Soltari Monk": "Creature", "Soltari Priest": "Creature",
            "Reflecting Pool": "Land",
        ],
        cardManaCosts: [
            "Blood Frenzy": "{1}{R}", "Fireslinger": "{1}{R}",
            "Goblin Bombardment": "{1}{R}", "Kindle": "{1}{R}",
            "Lightning Blast": "{3}{R}", "Mogg Conscripts": "{R}",
            "Rathi Dragon": "{2}{R}{R}", "Rolling Thunder": "{X}{R}{R}",
            "Scorched Earth": "{X}{R}", "Disenchant": "{1}{W}",
            "Field of Souls": "{2}{W}{W}", "Knight of Dawn": "{2}{W}",
            "Soltari Crusader": "{2}{W}", "Soltari Foot Soldier": "{W}",
            "Soltari Monk": "{W}{W}", "Soltari Priest": "{W}{W}",
        ],
        source: "InQuest Magazine, circa 1997. Tempest-block era. Source: mtgsalvation.com.",
        description: "Red/White shadow aggro from the Tempest era. Soltari creatures with shadow are unblockable, while Fireslinger and Kindle provide removal. Blood Frenzy turns any shadow hit into a lethal blow. Goblin Bombardment sacrifices creatures for extra reach, and Rathi Dragon closes games fast."
    )

    // MARK: - Spotlight: Faerie

    static let spotlightFaerie = ClassicArchetype(
        id: "inquest-spotlight-faerie",
        name: "Spotlight: Faerie",
        era: "1995",
        format: "Type I",
        mainboard: [
            "An-Havva Inn": 1,
            "Argothian Pixies": 2,
            "Aysen Abbey": 3,
            "Desert Twister": 1,
            "Disenchant": 2,
            "Faerie Noble": 3,
            "Forbidden Lore": 1,
            "Forest": 11,
            "Giant Growth": 4,
            "Icy Manipulator": 1,
            "Island": 4,
            "Pendelhaven": 1,
            "Power Sink": 2,
            "Scryb Sprites": 4,
            "Sea Sprite": 4,
            "Strip Mine": 2,
            "Tropical Island": 2,
            "Unstable Mutation": 4,
            "Willow Faerie": 4,
            "Willow Priestess": 3,
            "Winter Blast": 1,
            "Zuran Orb": 1,
        ],
        cardSets: [
            "An-Havva Inn": "HML", "Argothian Pixies": "ATQ",
            "Aysen Abbey": "HML", "Desert Twister": "4ED",
            "Disenchant": "4ED", "Faerie Noble": "HML",
            "Forbidden Lore": "ICE", "Giant Growth": "4ED",
            "Icy Manipulator": "4ED", "Pendelhaven": "LEG",
            "Power Sink": "4ED", "Scryb Sprites": "4ED",
            "Sea Sprite": "HML", "Strip Mine": "ATQ",
            "Tropical Island": "3ED", "Unstable Mutation": "4ED",
            "Willow Faerie": "HML", "Willow Priestess": "HML",
            "Winter Blast": "LEG", "Zuran Orb": "ICE",
            "Forest": "ICE", "Island": "ICE",
        ],
        cardTypes: [
            "An-Havva Inn": "Sorcery", "Argothian Pixies": "Creature",
            "Aysen Abbey": "Land", "Desert Twister": "Sorcery",
            "Disenchant": "Instant", "Faerie Noble": "Creature",
            "Forbidden Lore": "Enchantment", "Giant Growth": "Instant",
            "Icy Manipulator": "Artifact", "Pendelhaven": "Land",
            "Power Sink": "Instant", "Scryb Sprites": "Creature",
            "Sea Sprite": "Creature", "Strip Mine": "Land",
            "Tropical Island": "Land", "Unstable Mutation": "Enchantment",
            "Willow Faerie": "Creature", "Willow Priestess": "Creature",
            "Winter Blast": "Sorcery", "Zuran Orb": "Artifact",
        ],
        cardManaCosts: [
            "An-Havva Inn": "{1}{G}{G}", "Argothian Pixies": "{1}{G}",
            "Desert Twister": "{4}{G}{G}", "Disenchant": "{1}{W}",
            "Faerie Noble": "{2}{G}", "Forbidden Lore": "{2}{G}",
            "Giant Growth": "{G}", "Icy Manipulator": "{4}",
            "Power Sink": "{X}{U}", "Scryb Sprites": "{G}",
            "Sea Sprite": "{1}{U}", "Unstable Mutation": "{U}",
            "Willow Faerie": "{1}{G}", "Willow Priestess": "{2}{G}{G}",
            "Winter Blast": "{X}{G}", "Zuran Orb": "{0}",
        ],
        source: "InQuest Magazine Spotlight insert card, circa 1995-1996. Source: tappedout.net (user Alcoholix).",
        description: "Green/Blue faerie tribal. Willow Priestess cheats faeries into play, Faerie Noble lords the tribe, and Unstable Mutation turns tiny flyers into serious threats. Scryb Sprites and Sea Sprite provide evasive damage while Pendelhaven keeps 1/1s alive."
    )

    // MARK: - Spotlight: Zombie

    static let spotlightZombie = ClassicArchetype(
        id: "inquest-spotlight-zombie",
        name: "Spotlight: Zombie",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Bad Moon": 2,
            "Balduvian Dead": 1,
            "Dark Ritual": 4,
            "Drain Life": 2,
            "Evil Presence": 2,
            "Feast of the Unicorn": 2,
            "Feast or Famine": 3,
            "Gangrenous Zombies": 4,
            "Infernal Darkness": 1,
            "Lake of the Dead": 1,
            "Legions of Lim-Dul": 4,
            "Lim-Dul's Cohort": 3,
            "Oath of Lim-Dul": 1,
            "Pestilence": 1,
            "Phyrexian Boon": 2,
            "Pox": 1,
            "Scathe Zombies": 2,
            "Stench of Decay": 2,
            "Sulfurous Springs": 3,
            "Swamp": 17,
            "Zombie Master": 4,
        ],
        cardSets: [
            "Bad Moon": "4ED", "Balduvian Dead": "ALL", "Dark Ritual": "ICE",
            "Drain Life": "4ED", "Evil Presence": "4ED",
            "Feast of the Unicorn": "HML", "Feast or Famine": "ALL",
            "Gangrenous Zombies": "ICE", "Infernal Darkness": "ICE",
            "Lake of the Dead": "ALL", "Legions of Lim-Dul": "ICE",
            "Lim-Dul's Cohort": "ICE", "Oath of Lim-Dul": "ICE",
            "Pestilence": "4ED", "Phyrexian Boon": "ALL", "Pox": "ICE",
            "Scathe Zombies": "4ED", "Stench of Decay": "ALL",
            "Sulfurous Springs": "ICE", "Zombie Master": "4ED",
            "Swamp": "ICE",
        ],
        cardTypes: [
            "Bad Moon": "Enchantment", "Balduvian Dead": "Creature",
            "Dark Ritual": "Instant", "Drain Life": "Sorcery",
            "Evil Presence": "Enchantment", "Feast of the Unicorn": "Enchantment",
            "Feast or Famine": "Instant", "Gangrenous Zombies": "Creature",
            "Infernal Darkness": "Enchantment", "Lake of the Dead": "Land",
            "Legions of Lim-Dul": "Creature", "Lim-Dul's Cohort": "Creature",
            "Oath of Lim-Dul": "Enchantment", "Pestilence": "Enchantment",
            "Phyrexian Boon": "Enchantment", "Pox": "Sorcery",
            "Scathe Zombies": "Creature", "Stench of Decay": "Instant",
            "Sulfurous Springs": "Land", "Zombie Master": "Creature",
        ],
        cardManaCosts: [
            "Bad Moon": "{1}{B}", "Balduvian Dead": "{3}{B}",
            "Dark Ritual": "{B}", "Drain Life": "{X}{1}{B}",
            "Evil Presence": "{B}", "Feast of the Unicorn": "{3}{B}",
            "Feast or Famine": "{3}{B}", "Gangrenous Zombies": "{1}{B}{B}",
            "Infernal Darkness": "{2}{B}{B}", "Legions of Lim-Dul": "{1}{B}{B}",
            "Lim-Dul's Cohort": "{1}{B}{B}", "Oath of Lim-Dul": "{3}{B}",
            "Pestilence": "{2}{B}{B}", "Phyrexian Boon": "{1}{B}{B}",
            "Pox": "{B}{B}{B}", "Scathe Zombies": "{2}{B}",
            "Stench of Decay": "{1}{B}{B}", "Zombie Master": "{1}{B}{B}",
        ],
        source: "InQuest Magazine Spotlight insert card, circa 1995-1996. Source: tappedout.net (user Alcoholix).",
        description: "Mono-Black zombie tribal from the Ice Age era. Zombie Master gives all zombies swampwalk and regeneration, Bad Moon pumps them, and Gangrenous Zombies provide a board wipe that leaves your regenerating zombies standing. Lake of the Dead enables explosive mana plays."
    )

    // MARK: - Spotlight: Giants

    static let spotlightGiants = ClassicArchetype(
        id: "inquest-spotlight-giants",
        name: "Spotlight: Giants",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Bone Shaman": 1,
            "Craw Giant": 1,
            "Crumble": 2,
            "Fireball": 2,
            "Frost Giant": 1,
            "Giant Growth": 3,
            "Giant Strength": 3,
            "Hill Giant": 4,
            "Hurricane": 1,
            "Karplusan Forest": 4,
            "Karplusan Giant": 2,
            "Lightning Bolt": 4,
            "Pyroclasm": 1,
            "Regrowth": 1,
            "Snow-Covered Forest": 7,
            "Snow-Covered Mountain": 10,
            "Sol Ring": 1,
            "Stone Giant": 4,
            "The Brute": 1,
            "Tinder Wall": 4,
            "Tor Giant": 3,
            "Tranquility": 1,
            "Two-Headed Giant of Foriys": 1,
        ],
        cardSets: [
            "Bone Shaman": "ICE", "Craw Giant": "LEG", "Crumble": "ATQ",
            "Fireball": "4ED", "Frost Giant": "ICE", "Giant Growth": "4ED",
            "Giant Strength": "ICE", "Hill Giant": "4ED", "Hurricane": "4ED",
            "Karplusan Forest": "ICE", "Karplusan Giant": "ICE",
            "Lightning Bolt": "4ED", "Pyroclasm": "ICE", "Regrowth": "4ED",
            "Sol Ring": "3ED", "Stone Giant": "4ED", "The Brute": "4ED",
            "Tinder Wall": "ICE", "Tor Giant": "ICE", "Tranquility": "4ED",
            "Two-Headed Giant of Foriys": "4ED",
            "Snow-Covered Forest": "ICE", "Snow-Covered Mountain": "ICE",
        ],
        cardTypes: [
            "Bone Shaman": "Creature", "Craw Giant": "Creature",
            "Crumble": "Instant", "Fireball": "Sorcery",
            "Frost Giant": "Creature", "Giant Growth": "Instant",
            "Giant Strength": "Enchantment", "Hill Giant": "Creature",
            "Hurricane": "Sorcery", "Karplusan Forest": "Land",
            "Karplusan Giant": "Creature", "Lightning Bolt": "Instant",
            "Pyroclasm": "Sorcery", "Regrowth": "Sorcery",
            "Sol Ring": "Artifact", "Stone Giant": "Creature",
            "The Brute": "Enchantment", "Tinder Wall": "Creature",
            "Tor Giant": "Creature", "Tranquility": "Sorcery",
            "Two-Headed Giant of Foriys": "Creature",
        ],
        cardManaCosts: [
            "Bone Shaman": "{2}{R}{R}", "Craw Giant": "{3}{G}{G}{G}{G}",
            "Crumble": "{G}", "Fireball": "{X}{R}",
            "Frost Giant": "{3}{R}{R}", "Giant Growth": "{G}",
            "Giant Strength": "{R}{R}", "Hill Giant": "{3}{R}",
            "Hurricane": "{X}{G}", "Karplusan Giant": "{6}{R}",
            "Lightning Bolt": "{R}", "Pyroclasm": "{1}{R}",
            "Regrowth": "{1}{G}", "Sol Ring": "{1}",
            "Stone Giant": "{2}{R}{R}", "The Brute": "{1}{R}",
            "Tinder Wall": "{G}", "Tor Giant": "{3}{R}",
            "Tranquility": "{1}{G}",
            "Two-Headed Giant of Foriys": "{4}{R}",
        ],
        source: "InQuest Magazine Spotlight insert card, circa 1995-1996. Source: tappedout.net and mtggoldfish.com.",
        description: "Red/Green giant tribal. Stone Giant flings smaller creatures for damage, Two-Headed Giant of Foriys tramples over blockers, and Karplusan Giant provides snow-powered beef. Tinder Wall ramps into early giants while Giant Strength pumps them further."
    )

    // MARK: - Spotlight: Minotaur

    static let spotlightMinotaur = ClassicArchetype(
        id: "inquest-spotlight-minotaur",
        name: "Spotlight: Minotaur",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Aether Storm": 4,
            "An-Havva Township": 4,
            "Anaba Shaman": 4,
            "Anaba Spirit Crafter": 4,
            "Balance": 1,
            "Didgeridoo": 4,
            "Disenchant": 3,
            "Fireball": 4,
            "Hurloon Minotaur": 4,
            "Hurricane": 1,
            "Island": 3,
            "Jokulhaups": 1,
            "Labyrinth Minotaur": 4,
            "Land Cap": 2,
            "Maze of Ith": 1,
            "Mountain": 8,
            "Plateau": 1,
            "Regrowth": 1,
            "Sol Ring": 1,
            "Soul Barrier": 4,
            "Strip Mine": 1,
            "Veldt": 1,
            "Volcanic Island": 3,
            "Zuran Orb": 1,
        ],
        cardSets: [
            "Aether Storm": "HML", "An-Havva Township": "HML",
            "Anaba Shaman": "HML", "Anaba Spirit Crafter": "HML",
            "Balance": "4ED", "Didgeridoo": "HML", "Disenchant": "4ED",
            "Fireball": "4ED", "Hurloon Minotaur": "4ED", "Hurricane": "4ED",
            "Jokulhaups": "ICE", "Labyrinth Minotaur": "HML",
            "Land Cap": "ICE", "Maze of Ith": "DRK", "Plateau": "3ED",
            "Regrowth": "4ED", "Sol Ring": "3ED", "Soul Barrier": "ICE",
            "Strip Mine": "ATQ", "Veldt": "ICE", "Volcanic Island": "3ED",
            "Zuran Orb": "ICE",
            "Mountain": "ICE", "Island": "ICE",
        ],
        cardTypes: [
            "Aether Storm": "Enchantment", "An-Havva Township": "Land",
            "Anaba Shaman": "Creature", "Anaba Spirit Crafter": "Creature",
            "Balance": "Sorcery", "Didgeridoo": "Artifact",
            "Disenchant": "Instant", "Fireball": "Sorcery",
            "Hurloon Minotaur": "Creature", "Hurricane": "Sorcery",
            "Jokulhaups": "Sorcery", "Labyrinth Minotaur": "Creature",
            "Land Cap": "Land", "Maze of Ith": "Land",
            "Plateau": "Land", "Regrowth": "Sorcery",
            "Sol Ring": "Artifact", "Soul Barrier": "Enchantment",
            "Strip Mine": "Land", "Veldt": "Land",
            "Volcanic Island": "Land", "Zuran Orb": "Artifact",
        ],
        cardManaCosts: [
            "Aether Storm": "{3}{U}", "Anaba Shaman": "{3}{R}",
            "Anaba Spirit Crafter": "{2}{R}{R}", "Balance": "{1}{W}",
            "Didgeridoo": "{1}", "Disenchant": "{1}{W}",
            "Fireball": "{X}{R}", "Hurloon Minotaur": "{1}{R}{R}",
            "Hurricane": "{X}{G}", "Jokulhaups": "{4}{R}{R}",
            "Labyrinth Minotaur": "{3}{U}", "Regrowth": "{1}{G}",
            "Sol Ring": "{1}", "Soul Barrier": "{2}{U}",
            "Zuran Orb": "{0}",
        ],
        source: "InQuest Magazine Spotlight insert card, circa 1995-1996. Source: tappedout.net and deckstats.net.",
        description: "Five-color Minotaur tribal built around Didgeridoo — a 3-mana artifact that puts any Minotaur from your hand directly into play for just 3 mana. Anaba Spirit Crafter lords the tribe with +1/+1, Aether Storm and Soul Barrier punish opponents for casting creatures, then Jokulhaups resets the board."
    )

    // MARK: - Spotlight: Primates

    static let spotlightPrimates = ClassicArchetype(
        id: "inquest-spotlight-primates",
        name: "Spotlight: Primates",
        era: "1995",
        format: "Type I",
        mainboard: [
            "Barbary Apes": 4,
            "Kird Ape": 4,
            "Gorilla Berserkers": 3,
            "Gorilla Chieftain": 2,
            "Gorilla Shaman": 2,
            "Gargantuan Gorilla": 1,
            "Gorilla Pack": 1,
            "Guerrilla Tactics": 4,
            "Giant Growth": 3,
            "Bestial Fury": 2,
            "Hurricane": 2,
            "Primitive Justice": 2,
            "Gorilla War Cry": 1,
            "Lure": 1,
            "Surge of Strength": 1,
            "Tranquility": 1,
            "Wheel of Fortune": 1,
            "Sol Ring": 1,
            "Whalebone Glider": 1,
            "Snow-Covered Forest": 8,
            "Mountain": 5,
            "Karplusan Forest": 4,
            "Taiga": 4,
            "Strip Mine": 2,
        ],
        cardSets: [
            "Barbary Apes": "LEG", "Kird Ape": "ARN",
            "Gorilla Berserkers": "ALL", "Gorilla Chieftain": "ALL",
            "Gorilla Shaman": "ALL", "Gargantuan Gorilla": "ALL",
            "Gorilla Pack": "ICE", "Guerrilla Tactics": "ALL",
            "Giant Growth": "4ED", "Bestial Fury": "ALL",
            "Hurricane": "4ED", "Primitive Justice": "ALL",
            "Gorilla War Cry": "ALL", "Lure": "4ED",
            "Surge of Strength": "ALL", "Tranquility": "4ED",
            "Wheel of Fortune": "4ED", "Sol Ring": "3ED",
            "Whalebone Glider": "ALL", "Karplusan Forest": "ICE",
            "Taiga": "3ED", "Strip Mine": "ATQ",
            "Snow-Covered Forest": "ICE", "Mountain": "ICE",
        ],
        cardTypes: [
            "Barbary Apes": "Creature", "Kird Ape": "Creature",
            "Gorilla Berserkers": "Creature", "Gorilla Chieftain": "Creature",
            "Gorilla Shaman": "Creature", "Gargantuan Gorilla": "Creature",
            "Gorilla Pack": "Creature", "Guerrilla Tactics": "Instant",
            "Giant Growth": "Instant", "Bestial Fury": "Enchantment",
            "Hurricane": "Sorcery", "Primitive Justice": "Sorcery",
            "Gorilla War Cry": "Instant", "Lure": "Enchantment",
            "Surge of Strength": "Instant", "Tranquility": "Sorcery",
            "Wheel of Fortune": "Sorcery", "Sol Ring": "Artifact",
            "Whalebone Glider": "Artifact", "Karplusan Forest": "Land",
            "Taiga": "Land", "Strip Mine": "Land",
        ],
        cardManaCosts: [
            "Barbary Apes": "{1}{G}", "Kird Ape": "{R}",
            "Gorilla Berserkers": "{3}{G}{G}", "Gorilla Chieftain": "{2}{G}{G}",
            "Gorilla Shaman": "{R}", "Gargantuan Gorilla": "{4}{G}{G}{G}",
            "Gorilla Pack": "{2}{G}", "Guerrilla Tactics": "{1}{R}",
            "Giant Growth": "{G}", "Bestial Fury": "{2}{R}",
            "Hurricane": "{X}{G}", "Primitive Justice": "{1}{R}",
            "Gorilla War Cry": "{1}{R}", "Lure": "{1}{G}",
            "Surge of Strength": "{R}{G}", "Tranquility": "{1}{G}",
            "Wheel of Fortune": "{2}{R}", "Sol Ring": "{1}",
            "Whalebone Glider": "{2}",
        ],
        source: "InQuest Magazine Spotlight insert card, circa 1995-1996. Source: mtgsalvation.com.",
        description: "Red/Green ape and gorilla tribal. Kird Ape and Barbary Apes provide efficient early beats, Gorilla Shaman destroys cheap artifacts, and Gargantuan Gorilla is the 7/7 finisher that fights opposing creatures. Guerrilla Tactics doubles as removal and discard-punishment, Gorilla War Cry gives trample for alpha strikes."
    )
}
