import Foundation

// MARK: - Reserved List

/// The complete Magic: The Gathering Reserved List — Wizards of the Coast's
/// 1996 promise to never reprint these 571 cards. Organized by card type.
/// Sources: Scryfall (is:reserved query), MTG Wiki.
enum ReservedList {

    static let all: [LandCategory] = [
        lands,
        artifacts,
        enchantments,
        creatures,
        instantsAndSorceries,
    ]

    // MARK: - Lands (45 cards)

    static let lands = LandCategory(
        id: "rl-lands",
        name: "Reserved List Lands",
        iconName: "map.fill",
        description: "All 45 lands on the Reserved List. Includes the 10 original dual lands, the Urza's Saga 'Cradle cycle,' Bazaar of Baghdad, Library of Alexandria, Mishra's Workshop, The Tabernacle at Pendrell Vale, and other unique early-era lands. Sources: Scryfall, MTG Wiki.",
        cardNames: [
            "Badlands",
            "Balduvian Trading Post",
            "Bayou",
            "Bazaar of Baghdad",
            "City of Shadows",
            "City of Traitors",
            "Diamond Valley",
            "Elephant Graveyard",
            "Gaea's Cradle",
            "Griffin Canyon",
            "Halls of Mist",
            "Heart of Yavimaya",
            "Island of Wak-Wak",
            "Kjeldoran Outpost",
            "Lake of the Dead",
            "Land Cap",
            "Lava Tubes",
            "Library of Alexandria",
            "Lotus Vale",
            "Mishra's Workshop",
            "Plateau",
            "Rainbow Vale",
            "River Delta",
            "Savannah",
            "Scorched Ruins",
            "Scrubland",
            "Serra's Sanctum",
            "Sheltered Valley",
            "Soldevi Excavations",
            "Sorrow's Path",
            "Taiga",
            "Teferi's Isle",
            "The Tabernacle at Pendrell Vale",
            "Thawing Glaciers",
            "Timberline Ridge",
            "Tolarian Academy",
            "Tropical Island",
            "Tundra",
            "Underground Sea",
            "Undiscovered Paradise",
            "Veldt",
            "Volcanic Island",
            "Volrath's Stronghold",
            "Winding Canyons",
            "Yavimaya Hollow",
        ]
    )

    // MARK: - Artifacts (86 cards)

    static let artifacts = LandCategory(
        id: "rl-artifacts",
        name: "Reserved List Artifacts",
        iconName: "gearshape.fill",
        description: "All 86 artifacts on the Reserved List. Includes Black Lotus, the five Moxen, Time Vault, Candelabra of Tawnos, Lion's Eye Diamond, Mox Diamond, Grim Monolith, Memory Jar, and dozens more. Sources: Scryfall, MTG Wiki.",
        cardNames: [
            "Acidic Dagger",
            "Aegis of the Meek",
            "Aeolipile",
            "Al-abara's Carpet",
            "Alchor's Tomb",
            "Amulet of Quoz",
            "Amulet of Unmaking",
            "Anvil of Bogardan",
            "Apocalypse Chime",
            "Ashnod's Cylix",
            "Balm of Restoration",
            "Black Lotus",
            "Bone Mask",
            "Bosium Strip",
            "Bubble Matrix",
            "Candelabra of Tawnos",
            "Chaos Orb",
            "City in a Bottle",
            "Conch Horn",
            "Cursed Scroll",
            "Cyclopean Tomb",
            "Delif's Cube",
            "Diamond Kaleidoscope",
            "Didgeridoo",
            "Draconian Cylix",
            "Elven Lyre",
            "Floodwater Dam",
            "Forcefield",
            "Forethought Amulet",
            "Gauntlet of Might",
            "Golgothian Sylex",
            "Grim Monolith",
            "Gustha's Scepter",
            "Helm of Obedience",
            "Ice Cauldron",
            "Illusionary Mask",
            "Implements of Sacrifice",
            "Jester's Mask",
            "Knowledge Vault",
            "Lifeline",
            "Life Matrix",
            "Lion's Eye Diamond",
            "Lodestone Bauble",
            "Mana Matrix",
            "Mana Web",
            "Mangara's Tome",
            "Memory Jar",
            "Mightstone",
            "Mirror Universe",
            "Misers' Cage",
            "Mox Diamond",
            "Mox Emerald",
            "Mox Jet",
            "Mox Pearl",
            "Mox Ruby",
            "Mox Sapphire",
            "North Star",
            "Nova Pentacle",
            "Null Rod",
            "Paupers' Cage",
            "Phyrexian Portal",
            "Planar Gate",
            "Powder Keg",
            "Pyramids",
            "Razor Pendulum",
            "Ring of Gix",
            "Ring of Immortals",
            "Ring of Ma'ruf",
            "Ring of Renewal",
            "Sandals of Abdallah",
            "Sands of Time",
            "Soldevi Digger",
            "Spirit Shield",
            "Stone Calendar",
            "Sword of the Ages",
            "Tawnos's Coffin",
            "Temporal Aperture",
            "Thran Tome",
            "Time Vault",
            "Triangle of War",
            "Urza's Miter",
            "Ventifact Bottle",
            "Weakstone",
            "Well of Knowledge",
            "Xanthic Statue",
            "Zelyon Sword",
        ]
    )

    // MARK: - Enchantments (127 cards)

    static let enchantments = LandCategory(
        id: "rl-enchantments",
        name: "Reserved List Enchantments",
        iconName: "sparkles",
        description: "All 127 enchantments on the Reserved List. Includes Moat, The Abyss, Chains of Mephistopheles, Survival of the Fittest, Recurring Nightmare, Humility, Fastbond, Earthcraft, Aluren, and many more. Sources: Scryfall, MTG Wiki.",
        cardNames: [
            "Afiya Grove",
            "Aluren",
            "Ancestral Knowledge",
            "An-Zerrin Ruins",
            "Aysen Highway",
            "Bazaar of Wonders",
            "Blizzard",
            "Brand of Ill Omen",
            "Breathstealer's Crypt",
            "Cadaverous Bloom",
            "Call to Arms",
            "Carnival of Souls",
            "Caverns of Despair",
            "Chains of Mephistopheles",
            "Chaosphere",
            "Chromatic Armor",
            "Circle of Despair",
            "City of Solitude",
            "Copy Artifact",
            "Corrosion",
            "Cycle of Life",
            "Damping Field",
            "Divine Intervention",
            "Dream Halls",
            "Drop of Honey",
            "Dystopia",
            "Earthcraft",
            "Earthlink",
            "Elkin Lair",
            "Energy Storm",
            "Energy Vortex",
            "Equipoise",
            "Eye of Singularity",
            "Farmstead",
            "Fastbond",
            "Field of Dreams",
            "Flooded Shoreline",
            "Forsaken Wastes",
            "Fungal Bloom",
            "Fyndhorn Pollen",
            "Gate to Phyrexia",
            "Glacial Crevasses",
            "Goblin Bomb",
            "Gravity Sphere",
            "Grim Feast",
            "Hall of Gemstone",
            "Haunting Wind",
            "Heart of Bogardan",
            "Heat Stroke",
            "Hidden Path",
            "Hot Springs",
            "Humility",
            "Illusions of Grandeur",
            "Imprison",
            "Infinite Authority",
            "Infernal Tribute",
            "Inner Sanctum",
            "In the Eye of Chaos",
            "Invoke Prejudice",
            "Jihad",
            "Katabatic Winds",
            "Koskun Falls",
            "Kudzu",
            "Land Equilibrium",
            "Lich",
            "Lifeblood",
            "Lightning Cloud",
            "Living Plane",
            "Malignant Growth",
            "Mammoth Harness",
            "Mana Vortex",
            "Mesmeric Trance",
            "Mind Over Matter",
            "Moat",
            "Mudslide",
            "Mystic Decree",
            "Mystic Might",
            "Nature's Wrath",
            "Nether Void",
            "Null Chamber",
            "Oath of Ghouls",
            "Opal Archangel",
            "Opalescence",
            "Pendrell Mists",
            "Pillar Tombs of Aku",
            "Power Artifact",
            "Powerleech",
            "Preferred Selection",
            "Psychic Allergy",
            "Psychic Vortex",
            "Purgatory",
            "Raging River",
            "Reality Twist",
            "Recurring Nightmare",
            "Recycle",
            "Reparations",
            "Righteous War",
            "Ritual of Subdual",
            "Royal Decree",
            "Sarcomancy",
            "Season of the Witch",
            "Second Chance",
            "Serra Aviary",
            "Shimmer",
            "Snowblind",
            "Soul Echo",
            "Spiritual Sanctuary",
            "Splintering Wind",
            "Squandered Resources",
            "Storm World",
            "Suleiman's Legacy",
            "Survival of the Fittest",
            "Teferi's Realm",
            "The Abyss",
            "Thelon's Curse",
            "Thought Lash",
            "Tidal Control",
            "Tombstone Stairwell",
            "Tornado",
            "Tourach's Gate",
            "Treachery",
            "Unfulfilled Desires",
            "Wave of Terror",
            "Wellspring",
            "Winter's Night",
            "Worms of the Earth",
            "Yawgmoth's Bargain",
        ]
    )

    // MARK: - Creatures (232 cards)

    static let creatures = LandCategory(
        id: "rl-creatures",
        name: "Reserved List Creatures",
        iconName: "figure.stand",
        description: "All 232 creatures on the Reserved List (including artifact creatures). From format staples like Metalworker, Gilded Drake, Palinchron, and Sliver Queen to legendary figures like Juzam Djinn, Ali from Cairo, and Baron Sengir. Sources: Scryfall, MTG Wiki.",
        cardNames: [
            "Aboroth",
            "Academy Rector",
            "Adun Oakenshield",
            "Aku Djinn",
            "Ali from Cairo",
            "Anaba Ancestor",
            "Anaba Spirit Crafter",
            "Angus Mackenzie",
            "Argivian Archaeologist",
            "Argothian Wurm",
            "Asmira, Holy Avenger",
            "Auspicious Ancestor",
            "Autumn Willow",
            "Avenging Angel",
            "Avizoa",
            "Aysen Crusader",
            "Balduvian Hydra",
            "Baron Sengir",
            "Barrin, Master Wizard",
            "Bartel Runeaxe",
            "Beast Walkers",
            "Benthic Djinn",
            "Black Carriage",
            "Bogardan Phoenix",
            "Bone Dancer",
            "Boris Devilboon",
            "Brushwagg",
            "Canopy Dragon",
            "Catacomb Dragon",
            "Chaos Harlequin",
            "Chronatog",
            "Citanul Centaurs",
            "Citanul Druid",
            "Commander Greven il-Vec",
            "Covetous Dragon",
            "Crovax the Cursed",
            "Daughter of Autumn",
            "Demonic Hordes",
            "Deranged Hermit",
            "Discordant Spirit",
            "Dominating Licid",
            "Dwarven Armorer",
            "Dwarven Pony",
            "Dwarven Sea Clan",
            "Dwarven Thaumaturgist",
            "Ebon Praetor",
            "Eladamri, Lord of Leaves",
            "Elder Spawn",
            "Elvish Farmer",
            "Emberwilde Caliph",
            "Emberwilde Djinn",
            "Ertai's Familiar",
            "Ertai, Wizard Adept",
            "Escaped Shapeshifter",
            "Exalted Dragon",
            "Exorcist",
            "Faerie Noble",
            "Femeref Enchantress",
            "Firestorm Hellkite",
            "Firestorm Phoenix",
            "Flow of Maggots",
            "Frankenstein's Monster",
            "Frenetic Efreet",
            "Fungus Elemental",
            "Gaea's Avenger",
            "Gallowbraid",
            "Gargantuan Gorilla",
            "General Jarkeld",
            "Gilded Drake",
            "Goblin Flotilla",
            "Goblin Wizard",
            "Gosta Dirk",
            "Grandmother Sengir",
            "Granite Gargoyle",
            "Grave Robbers",
            "Great Whale",
            "Guardian Beast",
            "Guiding Spirit",
            "Gwendlyn Di Corci",
            "Hakim, Loreweaver",
            "Halfdane",
            "Hand of Justice",
            "Harbinger of Night",
            "Hazduhr the Abbot",
            "Hazezon Tamar",
            "Heart Wolf",
            "Herald of Serra",
            "Hivis of the Scale",
            "Homarid Shaman",
            "Icatian Lieutenant",
            "Icatian Skirmishers",
            "Ifh-Biff Efreet",
            "Illusionary Presence",
            "Infernal Denizen",
            "Ivory Gargoyle",
            "Jacques le Vert",
            "Jungle Patrol",
            "Juzam Djinn",
            "Karn, Silver Golem",
            "Kaysa",
            "Keeper of Tresserhorn",
            "Khabal Ghoul",
            "King Suleiman",
            "Kjeldoran Knight",
            "Kjeldoran Phalanx",
            "Knights of Thorn",
            "Kobold Overlord",
            "Kookus",
            "Krovikan Horror",
            "Kukemssa Pirates",
            "Lady Caleria",
            "Lady Evangela",
            "Leering Gargoyle",
            "Lichenthrope",
            "Liege of the Hollows",
            "Lightning Dragon",
            "Livonya Silone",
            "Lord of Tresserhorn",
            "Lurker",
            "Maraxus of Keld",
            "Marjhan",
            "Marton Stromgald",
            "Martyrs of Korlis",
            "Master of the Hunt",
            "Masticore",
            "Mercenaries",
            "Merchant Ship",
            "Metalworker",
            "Mindbender Spores",
            "Minion of Tevesh Szat",
            "Mist Dragon",
            "Mold Demon",
            "Morinfen",
            "Morphling",
            "Mountain Titan",
            "Multani, Maro-Sorcerer",
            "Musician",
            "Mwonvuli Ooze",
            "Nameless Race",
            "Narwhal",
            "Niall Silvain",
            "Ogre Enforcer",
            "Old Man of the Sea",
            "Orim, Samite Healer",
            "Palinchron",
            "Peacekeeper",
            "Phantasmal Sphere",
            "Phelddagrif",
            "Phyrexian Devourer",
            "Phyrexian Dreadnought",
            "Phyrexian Marauder",
            "Phyrexian Negator",
            "Pixie Queen",
            "Polar Kraken",
            "Preacher",
            "Purraj of Urborg",
            "Pygmy Hippo",
            "Quarum Trench Gnomes",
            "Quirion Druid",
            "Radiant, Archangel",
            "Ragnar",
            "Rainbow Efreet",
            "Ramses Overdark",
            "Rashida Scalebane",
            "Rasputin Dreamweaver",
            "Reveka, Wizard Savant",
            "River Merfolk",
            "Rock Basilisk",
            "Rock Hydra",
            "Roc of Kher Ridges",
            "Rofellos, Llanowar Emissary",
            "Rogue Skycaptain",
            "Rohgahh of Kher Keep",
            "Rysorian Badger",
            "Sawback Manticore",
            "Scarwood Bandits",
            "Sedge Troll",
            "Selenia, Dark Angel",
            "Serendib Djinn",
            "Shauku, Endbringer",
            "Sidar Jabari",
            "Silver Wyvern",
            "Singing Tree",
            "Skeleton Ship",
            "Sliver Queen",
            "Soldevi Golem",
            "Soraya the Falconer",
            "Spectral Guardian",
            "Spinal Villain",
            "Spirit of the Night",
            "Storm Spirit",
            "Subterranean Spirit",
            "Su-Chi",
            "Sustaining Spirit",
            "Sworn Defender",
            "Tainted Specter",
            "Taniwha",
            "Teeka's Dragon",
            "Teferi's Imp",
            "Telim'Tor",
            "Tetsuo Umezawa",
            "Thelonite Monk",
            "Thrull Champion",
            "Thunder Spirit",
            "Timmerian Fiends",
            "Tolarian Entrancer",
            "Tolarian Serpent",
            "Tracker",
            "Tuknir Deathlock",
            "Two-Headed Giant of Foriys",
            "Ur-Drago",
            "Urborg Stalker",
            "Varchild's War-Riders",
            "Veldrane of Sengir",
            "Vesuvan Doppelganger",
            "Veteran Bodyguard",
            "Viashivan Dragon",
            "Vodalian Knights",
            "Vodalian War Machine",
            "Volrath's Shapeshifter",
            "Wall of Kelp",
            "Wandering Mage",
            "Warping Wurm",
            "Weatherseed Treefolk",
            "Willow Priestess",
            "Willow Satyr",
            "Wood Elemental",
            "Wormwood Treefolk",
            "Zephid",
            "Zhalfirin Crusader",
            "Zirilan of the Claw",
            "Zuberi, Golden Feather",
        ]
    )

    // MARK: - Instants & Sorceries (81 cards)

    static let instantsAndSorceries = LandCategory(
        id: "rl-spells",
        name: "Reserved List Spells",
        iconName: "wand.and.stars",
        description: "All 81 instants and sorceries on the Reserved List. Includes Ancestral Recall, Time Walk, Timetwister, Wheel of Fortune, Yawgmoth's Will, Time Spiral, Fork, Intuition, and many more format-defining spells. Sources: Scryfall, MTG Wiki.",
        cardNames: [
            // Instants (38)
            "Abeyance",
            "Ancestral Recall",
            "Barreling Attack",
            "Blaze of Glory",
            "Carrion",
            "Chain Stasis",
            "Corpse Dance",
            "Debt of Loyalty",
            "Disharmony",
            "Divine Retribution",
            "Firestorm",
            "Fork",
            "Formation",
            "Gravebind",
            "Hatred",
            "Intuition",
            "Jabari's Influence",
            "Kaervek's Spite",
            "Lightning Blow",
            "Lure of Prey",
            "Meditate",
            "Natural Selection",
            "Omen of Fire",
            "Prismatic Lace",
            "Rapid Fire",
            "Reflect Damage",
            "Reverberation",
            "Shallow Grave",
            "Spoils of Evil",
            "Telekinesis",
            "Telim'Tor's Edict",
            "Three Wishes",
            "Tithe",
            "Trailblazer",
            "Urborg Justice",
            "Winter's Chill",
            "Word of Command",
            "Yare",
            // Sorceries (43)
            "Acid Rain",
            "All Hallow's Eve",
            "Altar of Bone",
            "Apocalypse",
            "Baki's Curse",
            "Braingeyser",
            "Cleanse",
            "Cleansing",
            "Contract from Below",
            "Darkpact",
            "Demonic Attorney",
            "Donate",
            "Energy Bolt",
            "Eternal Flame",
            "Eureka",
            "Falling Star",
            "Fatal Lore",
            "Forbidden Ritual",
            "Hellfire",
            "Jovial Evil",
            "Leeches",
            "Martyr's Cry",
            "Misfortune",
            "Natural Balance",
            "Paradigm Shift",
            "Phyrexian Purge",
            "Phyrexian Tribute",
            "Political Trickery",
            "Replenish",
            "Retribution of the Meek",
            "Ritual of the Machine",
            "Seeds of Innocence",
            "Shahrazad",
            "Spoils of War",
            "Time Spiral",
            "Timetwister",
            "Time Walk",
            "Torrent of Lava",
            "Transmute Artifact",
            "Typhoon",
            "Wheel of Fortune",
            "Winter Sky",
            "Yawgmoth's Will",
        ]
    )
}
